### ISSUE TITLE
improve usability of datatables

### ISSUE THREAD

**Issue by ymurase** [crest-cassia/oacis#238]
- A list is so long that pagination buttons are not easy to click.
    - put pagination buttons on top of the table as well as the bottom
- When the number of parameters are large, the table can horizontally too long.
    - try ColVis extension
        - http://datatables.net/extensions/colvis/
- would like to see the headers even when you scroll down the page
    - try FixedHeader extension
        - http://datatables.net/extensions/fixedheader
- do not show sorting for the right-most and left-most columns
    - follow this example
        - http://datatables.net/examples/api/counter_columns.html

**Comment by takeshi-uchitane** [comment]
jquery-datatables-railsに含まれるfixedHeaderはversion 2.1.2で2014年リリースと古く，互換性がない
colVisは開発が終了し，Buttonsという拡張機能を利用するように促されている
新しいgemはリリースされていない

以上のことから，datatablesをgemではなく，独自にインストールすることを考えたほうがよさそう
参考: http://dstull.github.io/javascript/2015/09/06/rails-datatables-install-without-gem/
/vender/assets以下にダウンロードして配置

**Comment by takeshi-uchitane** [comment]
ダウンロードしたソースを配置したところ，bootstrap3との相性問題で，ソートアイコンがうまく表示されない
- fixedHeaderは機能した
- ColVis(Buttonsに統合された)は，機能したが，見た目がサンプルと異なっていた

ダウンロードしたソースを配置する方法では，見た目が解決できないので断念
gemのdatatablesを利用し，fixedHeader機能を諦めた

**Comment by takeshi-uchitane** [comment]
closed #238 via #423
