### ISSUE TITLE
creating multiple runs are too slow

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#264]
BatchでPSやRunを作るときにRunを作るのが遅い。

bulk insert で高速化できるか調査する。
http://docs.mongodb.org/manual/core/bulk-inserts/
http://stackoverflow.com/questions/3772378/batch-insert-update-using-mongoid

batch_size (100くらい？）を事前に決めておき、その個数ごとにまとめてinsertできるようにする。
その際に、callbackでディレクトリを作ったりしているので適切にコールバックが呼ばれるようにハッキングする必要がある。

**Comment by takeshi-uchitane** [comment]
#315 と同じ．閉じる．
