### ISSUE TITLE
update recommended ruby version to 2.2.0

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#299]
Rubyの推奨バージョンを2.2.0に変更。
2.2.0で問題がないか一通りテストを実施する。
（GCなどの改善によりSSHの安定性が増すかも）

**Comment by takeshi-uchitane** [comment]
docker上で2.2を試したことがあります．
gemのインストールでこけていたはず．
- Ubuntu 14.04 64bit
- rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
- ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

eventmachine 1.0.3をeventmachine 1.0.4へ変更しないとbundle installが通らない

eventmachineのバージョンアップ後，bundle installが通ってもrspecが始まらない
>oacis@b5aa1aec1b27:~/oacis$ bundle exec rspec -c
/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.17/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/mongoid-3.1.6/lib/mongoid/persistence/atomic/operation.rb:74: warning: circular argument reference - field
/home/oacis/oacis/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- test/unit/assertions (LoadError)

この記事に答えがありそう
https://github.com/rspec/rspec-rails/issues/1273
> Rails hasn't officially started supporting Ruby 2.2 on Rails 3.2 yet

そして，rails4.2に上げるのは，手間がかかりますね．

**Comment by yohm** [comment]
なんかこれ聞いたことがあります。RSpecを３系統にあげたら解決しないですかね。
手間はかかりますが、そろそろやってもいいかも。

**Comment by takeshi-uchitane** [comment]
> 手間はかかりますが、そろそろやってもいいかも。

私もいい時期だと思います．
更新を重ねてきたことにより，テストやコメントにも細かな間違いがでてきているので，リファクタリングも兼ねて全体を見直す必要があると思います．

**Comment by yohm** [comment]
じゃあまずはRspec3にあげましょう。というわけでこちらを参考におねがいします！
http://qiita.com/jnchito/items/f86b57d27b44e6e7d1e9

**Comment by takeshi-uchitane** [comment]
rspec 2.99.0 で指摘された変更(pending, be_true, be_false, have().times, config.infer_spec_type_from_file_location!)を修正してrspec 3.2.0 へアップしましたが，やはりこけますね．
引き続き調査してみます．
Ubuntu 14.04
rvm 1.26.10
ruby 2.1.5p273

> Coverage report Rcov style generated for RSpec to /home/t-uchitane/git/oacis/coverage/rcov
/home/t-uchitane/git/oacis/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:634:in `method_missing': undefined method `its' for RSpec::ExampleGroups::ParameterSetQuery::Selector:Class (NoMethodError)

**Comment by takeshi-uchitane** [comment]
rails4へアップデートしたことで，ruby2.2がサポートされた． closed via #316
