### ISSUE TITLE
sort parameter sets by more than two keys

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#300]
ParameterSetのテーブルを２つ以上のキーでソートしたい。

例えば、2つのパラメータP1, P2があった時に、P1でソートした後、P1のソートは崩さずにP2でさらにソートするなど、パラメータのソートに優先順位をつけるみたいなことをしたい時がある。

**Comment by takeshi-uchitane** [comment]
dataTableにMultiple sortの機能有り．
https://datatables.net/examples/basic_init/multi_col_sort.html
（Shift keyを押しながら２番目の列を選択する．）

サーバーサイドの処理を追記する必要あり．
@view.params[:iSortCol_1]
@view.params[:sSortDir_1]
ドキュメントにも追記が必要？
