### ISSUE TITLE
cli create_runs sets _seed

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/oacis#304]
- It is required to set a special _seed for new runs created by oacis_cli.
  - For example, when initial conditions are given depending on _seed, it often is required to compare simulation results which are different from each other in parameter_set but have same initial conditions.

- Specification
  - Add a new argument `--seeds` in oacis_cll create_runs to create new runs.
  - New runs with seed=0, 1, 2 are created by the following command if the seeds are unique in the parameter_set.runs.
  ```sh
    ./bin/oacis_cli create_runs  -p parameter_set_ids.json -j job_parameter.json --seed "[0, 1, 2]" -o run_ids.json
  ```

**Comment by takeshi-uchitane** [comment]
num_runsはrunの数の上限なので--seedを与える場合でも必要

**Comment by yohm** [comment]
> num_runsはrunの数の上限なので--seedを与える場合でも必要

ということは最終的なCLIの仕様はどのようになります？

あるPSにseed=1のrunがあって、他のPSにはない場合に、`--seed "[1,2,3]"` を指定するとどういう挙動になりますか？
