### ISSUE TITLE
dateコマンドで日本語が返ってくる場合がある

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#319]
ジョブスクリプト内で以下のようにdateコマンドの出力結果をjsonに埋め込んでいる。

```job.sh
LANG=C

echo "  \\"started_at\\": \\"`date`\\"," >> ../${OACIS_RUN_ID}_status.json
```

この場合に、dateコマンドが日本語などの他のロケールで出力される場合がある。
http://d.hatena.ne.jp/sh2/20120704
LANGよりも、LC_ALL, LC_TIMEの優先順位が高いため。
ジョブスクリプト内でLC_ALLの環境変数をセットするように変更する。

**Comment by yohm** [comment]
@takeshi-uchitane 直近の実行で困っているので、こちらで対応します。

**Comment by takeshi-uchitane** [comment]
@yohm 了解しました．よろしくお願いします．

**Comment by yohm** [comment]
#330 が終了後とりかかる
