### ISSUE TITLE
 error log表示を充実させる

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/oacis#325]
# ログmodelの導入

## 必要な機能
- [ ] Job(Analysis) のエラートラッキング
- [ ] アクションの履歴トラッキング

### Job(Analysis) のエラートラッキング
- run, analysisに紐付け
- runのshow pageのタブに追加
- 表示内容[date, event, message](eventに色づけ)
-- event:["create", "ssh-connection", "preprocess", "submit", "job-status-check(only failed)", "download", "update"]
- 正常系

date	|event	|message                                                       |trace
------|------------|--------------------------------------------------------|--------------
15/06/02 13:06	|create	|Run(run_id) is created.	|--
15/06/03 13:10	|preprocess	|Preprocess is finished.	|--
15/06/04 13:15	|submit	|Xsub is successfully finished. job_id(job_id)	|--
15/06/05 13:20	|Job-status	|Run is finished.	|--
15/06/06 13:21	|download	|Run is downloaded.	|--
15/06/07 13:22	|update	|Run status is updated to finished.	|--

- 異常系

date	|event	|message                                                       |trace
------|------------|--------------------------------------------------------|--------------
15/06/02 13:06	|create	|Run(run_id) is created.	|--
15/06/03 13:10	|preprocess	|Preprocess is finished.	|--
15/06/04 13:15	|submit	|Xsub is successfully finished. job_id(job_id)	|--
15/06/05 13:20	|Job-status-failed(red-label)	|Run is failed.	|Link_to(detail)
15/06/06 13:21	|download-failed(red-label)	|Tar file does not exist. Download Run dir.	|--
15/06/07 13:22	|update-failed(red-label)	|Run status is updated to failed.(rc: -1)	|--

### アクションの履歴トラッキング
- Simに紐づけ
- Simのshow pageのタブに追加
- 表示内容[date, target, event, comment](target, eventに色づけ)
-- event:["create", "delete"](for ps, run, analyzer, analysis)
-- 表のsearchアイコンをクリックで関連するPSやRUNやAnalysesをmodalで表示
- PSやRunやAnalysesの作成，更新，削除
- 1ログ中に，複数のcollectionが含まれる

- ログ

date	|target	|event	|message	|search
------|------------|------------|------------|------------------
15/06/01 13:06	|analyzer	|create	|Analyzer_name for Run is crated	|analyzer_show
15/06/02 13:06	|parameter_sets	|create	|100 parameter sets are created.	|ps_table_modal
15/06/03 13:06	|runs	|create	|200 runs are created	|runs_table_modal
15/06/03 13:22	|analyses	|create	|1 analysis for Run is automatically created.	|analysis_show
15/06/03 13:22	|analyses	|create	|1 analysis for Run is automatically created.	|analysis_show
…	|…	|…	|…	|…
15/06/03 13:22	|analyses	|create	|1 analysis for Run is automatically created.	|analysis_show
15/06/04 13:30	|analyzer	|update	|Analyzer_name is update.	|analyzer_show
15/06/05 13:30	|runs	|replace	|200 runs are replaced by CLI.	|runs_table_modal
15/06/06 14:00	|analyses	|create	|1 analyses for ParameterSet is created.	|analysis_show
15/06/07 14:10	|runs	|create	|1 run is created	|runs_table_modal
15/06/08 14:11	|analyses	|create	|1 analyses for Run is automatically created.	|analyses_table_modal
15/06/09 14:11	|runs	|delete	|1 run with 1 analysis is deleted. 	|--

### どうやって実現・可視化するか？
- トラッキングが２種類あるのでクラス, インターフェースも２通り用意する

**Comment by yohm** [comment]
## 現状の問題点

- ジョブ実行は様々な要因で失敗するが、すべてstatus=failedになるだけなのでエラー原因の特定が難しい。例えば以下のようなケースでエラーになりうる
  1. SSHの接続不安定性
  2. preprocessの失敗
  3. xsubの設定ミス
  4. jsonのパースエラー
- これらのエラーが起きたときにユーザーが簡単にエラーの原因を特定することがこのissueの目的

## 仕様案

- SSH接続不安定による場合と設定ミスの場合とで処理を分ける。
  - 前者の場合：現状のjob_worker_development.logのテキストログにエラーを残し、時間をあけてretryするようにする。この際、runのstatusは変更しない
  - 後者の場合：runに errors というフィールドを追加し、どの処理が原因でfailedになったかブラウザから確認できるようにする
