### ISSUE TITLE
Document for OACIS v2

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/oacis#340]
# 変更点のまとめ
- ソフトウェア要求
    - ruby2.2
    - xsub
- 内容
    - 後方互換性がなくなった

# バージョンアップ方法
- xsubの導入
- git pull

**Comment by yohm** [comment]
- analyzerのremote実行の追加
    - auto runにしていたAnalyzerは、自動実行のhostを指定しないと実行されない
