### ISSUE TITLE
省略したIDが同一になる

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#346]
IDの生成ロジックが変わったのか、同じIDになってしまう。

![image](https://cloud.githubusercontent.com/assets/718731/8567111/5bec5f04-256b-11e5-889a-f006c9af5b32.png)

**Comment by takeshi-uchitane** [comment]
runのseedをidから作成していたときに気づきましたが，下3byte(16進数で6桁)のカウンターが増え方が第5桁目からになっていて，16^2(5桁目と6桁目)を作り終えると，第3桁目が増え始めます．
id省略を省略するときは，epochの4byte(16進数で8桁)とカウンター3byte(16進数で6桁)を示さないと違いが見えないかと考えます．

- 提案1
  - 修正前: ce89..000
  - 修正後: ce89abcd..010000(epoch8桁+カウンター6桁)
- 提案2
  - 修正前: ce89..000
  - 修正後: abcd..010000(epochの下4桁+カウンター6桁)

**Comment by yohm** [comment]
長いので、epochの下４桁 + カウンターの上２桁で実用上いいんじゃないですか？

**Comment by takeshi-uchitane** [comment]
では6桁にしましょう．
間の".." も取り除きましょう
