### ISSUE TITLE
make run status error when host_parameter is invalid

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#350]
host_parameterが不正で、xsubが失敗している時にそのrunをerrorにしたい。
具体的にいうと、xsubでtorqueに対してジョブを投げる時に、OpenMPのスレッド数とppn(torqueのホストパラメータ）の整合性をチェックをしている。そこでエラーが起きた場合、ssh通信のエラーと判断されてrunのステータスが永遠に変わらない。
ssh通信に失敗した時はエラーを無視しても良いが、xsubの実行に失敗した時はrunをfailedにした方が良さそう。いかがでしょう？

**Comment by takeshi-uchitane** [comment]
xsubが0以外のリターンコードを返したら，値に応じてエラー処理を分岐してはいかがでしょうか？
xsubがリターンコードを返すのはssh通信エラーとは区別できると思います．

**Comment by takeshi-uchitane** [comment]
状況を再確認しました．
- 当初想定していたこと
    - xsubがインストールされていない
    - XSUB_TYPEが設定されていない
これらの間違いであればxsubを設定してもらえばjob自体に間違いは無いだろうと考えていました．

xsbuのvalidateionが失敗することを考慮するとjobのステータスはfaildにして，一度destoryしてもらうのが良さそうですね．対処します．

ちなみに，リターンコードは，
    - xsubコマンドが見当たらない場合: rc=>127
    - XSUB_TYPE の設定ミス: rc=>1
    - validationの失敗: rc=>1
なので，リターンコードで分類するのは現在のxsubの仕様では不可能なようです．
