### ISSUE TITLE
get list of ParameterSet IDs, Run IDs

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#354]
## 問題点

CLIでanalysisをまとめて投げる時に、あるParameterSetに属するRunIDの一覧、またはSimulatorに属するParameterSetの一覧を取得したい。
現状ではCLIでまとめてPSやRunを作成した場合のみ、IDの一覧が取得できる。

## 改善案

- Simulator, ParameterSetのshowページに、json表示へのリンクを作る。
- jsonの表示の中で子要素のIDの一覧を表示するようにする
  - Runの一覧の場合は、statusごとにIDを取れるようにする。
- ユーザーはそのIDの一覧をCLIに渡すことで、analysisがまとめて投げられるようになる

**Comment by takeshi-uchitane** [comment]
現状だと，ID一覧を獲得する方法はCLI経由しかないですね．
この機能が必要なことに同意します．

analysisを大量作成するとCLIのレスポンスは遅いかもしれません．調査してみます．
