### ISSUE TITLE
do not remove work directory in job script

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#359]
### 問題点

ジョブスクリプトで、ジョブ完了後にtar.bz2を作った後にworkディレクトリを削除している。
ジョブスケジューラの標準出力、エラー出力はこのディレクトリ内に出力することになっているが、ディレクトリが削除された後に出力がでることがある（I/Oのバッファの都合上）。
出力先のディレクトリがすでに削除されているので、出力の一部が抜けるだけでなく、ジョブスケジューラがエラーを返す。

### 対策案
- スクリプト内でworkディレクトリを削除するのはやめて、ダウンロード後に削除するようにする
  - ダウンロード可能かどうかの判定にはschedulerの出力を使っているので、ダウンロード時にはI/Oのバッファはすべて出ているはず
- すべての処理が完了したら、work_base_dir に `#{job_id}_archive_finished` というファイルをtouchで作成する。このファイルが存在したら.tar.bz2をダウンロードし、存在しなかったらwork_dirをダウンロードする。
  - 今の仕様では、結果をダウンロードするときにworkディレクトリの存在を使って、tar.bz2が正常終了したかを判定しているため。

**Comment by takeshi-uchitane** [comment]
kのようにステージングがある場合は，archive_finisedファイルもステージアウトするのでしょうか？
