### ISSUE TITLE
cannot change the default value of analysis parameters

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#413]
## 再現手順

Analyzerの編集画面で、parameterのデフォルト値を設定することができる。
**一度、analysisを作成した状態で** Analyzerを編集しパラメータのデフォルト値を変更すると「Analyzer was successfully updated」という表示がでるが実際には更新されない。

![image](https://cloud.githubusercontent.com/assets/718731/11892379/0307ad92-a5ab-11e5-83dc-48c63d23bf61.png)

**Comment by takeshi-uchitane** [comment]
# 原因
- updateの時にパラメータ名が:key の値として通知されない(createの時は通知される)
- より詳細には，:key, :typeが通知されない，代わりに"_destroy"が通知されている
```
  {"0"=>
    {"default"=>"1.0",
     "description"=>"",
     "_destroy"=>"false",
     "id"=>"5673c54c3739370345020000"}}
```
# analysisが作成されていない場合
- 挙動は正常に見える
```
  {"0"=>
    {"key"=>"TTT",
     "type"=>"Float",
     "default"=>"1.0",
     "description"=>"",
     "_destroy"=>"false",
     "id"=>"5673c54c3739370345020000"},
   "1450428357416"=>
    {"key"=>"RRR",
     "type"=>"Integer",
     "default"=>"10",
     "description"=>"",
     "_destroy"=>"false"}},
```
- analysisが存在するときのviewの設定を見直します．
- デフォルト値の変更についてテストを追加します．
