### ISSUE TITLE
Store results on remote storage

### ISSUE THREAD

**Issue by ymurase** [crest-cassia/oacis#44]
Currently, all the result files are stored on the server where rails application is running.
However, gathering all these files may cause performance degradation due to the file transfer over the network.
The files should be kept on the remote server.

**Comment by takeshi-uchitane** [comment]
シミュレータの実行スクリプトで環境変数OACIS_RUN_IDが取得可能なので，必要があればシミュレータの中でファイルを移動してもらう方針．閉じる．
