### ISSUE TITLE
tarは保存しない

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/oacis#440]
容量節約のため，tar.bz2を削除する．
tarのダウンロード機能は削除する．
パスが表示されるので，直接アクセスしてもらう方針．
READ ONLYで公開する時は，s3などにファイルを置いて直接アクセスしてもらう運用にする．

**Comment by yohm** [comment]
相談の結果、容量節約よりも素早くarchiveをダウンロードできるメリットの方が大きいと判断したのでこのissueはcloseする。
