### ISSUE TITLE
mode for storing _output.json only

### ISSUE THREAD

**Issue by ymurase** [crest-cassia/oacis#45]
For some simulators, we do not have to keep all the output files. 
Let's consider the optimization problem of traffic flow as an example.
What we need for this study is only some scalar variables such as traffic flow rates.
In that case, storing all the output files may cause performance degradation.

Add a flag to simulators which determines whether all the output files should be kept or not.
If the flag is on, results are not stored as files. Only the contents of the _output.json are stored in MongoDB.

**Comment by takeshi-uchitane** [comment]
シミュレータの中で，不要なファイルは削除してもらう方針．閉じる．
