### ISSUE TITLE
CLIでpsとrunを同時に作成するときrunの生成（実行）順番を変更する

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/oacis#475]
# 状況
- CLIからｐｓとrunを同時に作成すると，ｐｓの作成順にrunが実行される．
- 全てのpsの組み合わせに対し1runづつ実行されるほうが望ましい．
- runの生成順を変更する（実行順はrunの生成順になっている）
- ただし，CLIの実行時間は悪化する可能性あり
# 現在の実装

input.each do |ps_v|
crate_ps(v)
create_runs(ps, num_runs)
end
# 実装方法

pss=[]
input.each do |ps_v|
pss << crate_ps(v)
end
num_runs.times.do |i|
  pss.each do |ps|
    create_runs(ps, i)
  end
end

**Comment by yohm** [comment]
version3 から100以上のPSをGUIから作ることができるようになったので、このissueは優先度が低い。一度closeする。（どうしても必要であれば再度issueを作る）
