### ISSUE TITLE
give 0 or 1 for boolean parameters

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#526]
for simulators receiving input parameters as command line arguments, boolean parameters should be given by 1/0 rather than 'true'/'false' string.

**Comment by takeshi-uchitane** [comment]
In my case, a simulator has a boolean parameter. But the type of parameter was selected as "String". Thus, there was no problem for me.
Should we consider about that boolean type is needed or not?

By the way, will old simulators which has boolean parameters be modified by this enhancement?

**Comment by yohm** [comment]
I agree that Boolean parameters are not frequently used and they are replaceable with Integer or String parameters. Maybe, we can drop it in a future major version up.

As you said, this enhancement will break the backward compatibility. However, I'm sure that most of the users are not using boolean parameters with command-line argument inputs.
So let us change the specification in v2.12.0.
