### ISSUE TITLE
scheduler 開発用のデバッグモード

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#539]
scheduler 開発用に、デバッグモードがほしい。

OACIS で起動した時、scheduler に不具合があっても、実行時に作られる各種ファイルが、
ジョブ終了時に消されてしまうので、実際どんなスクリプトが作成され、計算ノードに
どんな指令がいったのか、などの確認がやりにくい。

デバッグモードを用意して、作業ファイルを消さないモードが有ったほうが、いろいろやりやすい気がする。

**Comment by yohm** [comment]
デバッグモードあったほうが良さそうですね。
(1) simulatorの設定項目でdebug modeをon/off切り替えられるようにする
(2) debug modeがonの場合はリモートサーバーの作業ファイルを消さない
という仕様を導入しようかと思います。
