### ISSUE TITLE
cannot delete parameter definitions of Analyzer

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#540]
When we edit Analyzer and delete the definition of parameters, the Analyzer is not properly updated. The deleted parameter definition still remains.

**Comment by takeshi-uchitane** [comment]
The next url may be a solution to remove parameter definitions.
https://stackoverflow.com/questions/24584816/rails-4-deleting-nested-attributes-works-on-create-but-not-on-edit-update

From the reason, it is required to edit controller and view with rspec.
It will take one more day.
