### ISSUE TITLE
チュートリアルのページの問題など

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#541]
現在、チュートリアルページで、ブラウザの幅が狭いと、上のほうが隠れてしまう。うまくならないか？

![screenshot_2017-12-26_18-06-52](https://user-images.githubusercontent.com/5162624/34352725-9beeee00-ea67-11e7-8489-935ddc23d9b1.png)

**Comment by noda50** [comment]
その他、気づいたこと（１）
「2. Simulator登録」のところで、シミュレータは _output.json をいじってはいけないと書いてあるが、「5. 結果の確認」のところでは、 _output.json に結果を出力すると、プロットなどができると書いてある。

**Comment by noda50** [comment]
気づいたこと（２）
"Parameter Set" へのページに、簡単に行けない。
私が試したところ、Parameter Set のページに行くには、
  (1) Simulators のページで、シミュレータを選ぶ。
  (2) Simulators/foo0 のページで、"Parameter Sets" のタブを選んで、さらに、 Parameter Set の虫眼鏡マークを選ぶ。("foo0" は仮のシミュレータ名)
  (3) ポップアップで出て来る "Runs on" のページで、 "RunID" の１つを選ぶ。
  (4) "Run" のページの上部の、"Simulators/foo0/Param:xxxxx/..." の "Param:" のところを選ぶ。
  (5) これで、やっと、Parameter Set のページに飛ぶ。

**Comment by yohm** [comment]
フィードバックありがとうございます。

> 上の方が隠れてしまう

ここの位置はJSで微修正していて、そのせいで表示が乱れるのだと思います。適宜直していきます。

> 気づいたこと（１）

こちらについては文面を改善します。

> 気づいたこと（２）

こちらはSimulatorを選択して、(2)の時点で虫眼鏡ではなく、IDをクリックすればparameter setのページに飛べます。

![image](https://user-images.githubusercontent.com/718731/34368044-32c1ea9e-eaf4-11e7-8b7f-69ab5c721f67.png)

**Comment by yohm** [comment]
#561 でドキュメントを改善
