### ISSUE TITLE
Parameter Set の生成ページでのエラー

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#542]
"Create a new parameter set" のページで、コマンドラインではうまく作れるセットが、うまく作れない例がある。

例えば以下のコマンドラインに相当するものを作ろうとすると、

> The  form contains 1 error
> *No parameter_set was created となる。

`./bin/oacis_cli create_parameter_sets -s 5a422d41d44bd9e90c21d621 -i '{"param1":[11,23],"param2":[5,6,7,8,9,10],"param3":[2,3,5,7,11,13,17,19]}' -r '{"num_runs":1,"mpi_procs":0,"omp_threads":0,"priority":1,"submitted_to":"5a421234d44bd9e90c21d533","host_parameters":null}' -o ps.json
`

生成するパラメータの組み合わせ数の問題？

![_2017-12-26_20-26-22](https://user-images.githubusercontent.com/5162624/34355736-0f5f73b0-ea7b-11e7-9eab-a36292e2e705.png)

**Comment by yohm** [comment]
こちらは意図的にそうしています。100PSを超えるとレスポンスに時間がかかることがあり、ブラウザ上からはプログレスも見えないし、キャンセルもできないのでこのようにしています。CLIから作ってもらう必要があります。
この意図がわかりやすくなるように今後UIを改良しようと思います。

**Comment by noda50** [comment]
了解。
少なくとも、エラーメッセージは変えたほうが良いね。
例えば、
"Error: too many runs.  In order to run whole combination, please use CLI command below." とか。
