### ISSUE TITLE
計算ノードで終了しているのに、その状態を取ってこれない問題

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#543]
野田の環境で、計算ノードで計算が終了しているのに、それがOACISのサーバ側で認識できない問題が発生している。

oacis を動かしてみて、ローカルマシンを計算ノードとして登録して動かすと順調に行くが、
リモートのマシンをホスト登録してそちらに投げるようにすると、最初の run が投げられた後、その run がリモートで終わっているのに、サーバに反映されない。
run のワーキング ファイル等も残っているので、結果を取得しに行っていないように見える。

何が問題か解明したいが、手がかりがない。
ありそうなものとして、リモート側の環境がちゃんとできていないとかがありえるかもしれない。
例えば、野田個人は tcsh を使っていて、bash の環境をちゃんと整備していないので、そのあたりでどこか引っかかっている可能性はありそう。ただ、どこでこけているのか不明。

**Comment by noda50** [comment]
原因、ちょっと分かってきた。
log file のうち、”job_observer_worker.log” というのを見ると、

> ERROR  -- : Error in RemoteJobHandler#remote_status: #<RuntimeError: can not move work_directory from ~/tmp/OACIS/5a44b6b09d409b71327ea519>

というのがあった。ただ、リモートホストには、このディレクトリは存在している。（ちゃんと実行結果も残っている）

**Comment by noda50** [comment]
解明。

mounted_work_base_dir を設定していたため。
間違いを割けるために、host の入力のところで、説明を入れたほうが良くないか？
例えば、
>  required only when the host is localhost or the remote working directory is mounted from the localhost.

**Comment by noda50** [comment]
チュートリアルでの例が、mounted_work_base_dir を設定するものになっているのも、ちょっと誤解を招きやすい気がする。

**Comment by yohm** [comment]
解決され多様で何よりです。
ご指摘はもっともで、他にもちょくちょくmounted_work_base_dirの設定を間違える人がいます。年明けにドキュメントの改善を行います。それから今年度中にUIの改善を依頼しているので、年度内にはUI上でもわかりやすいようにしたいと思います。
