### ISSUE TITLE
Errno::ENOENT in Runs#show

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#545]
終了した Run を見ようとして、以下のエラー。

> Showing /home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/views/runs/_results.html.haml where line #3 raised:
>
> No such file or directory @ dir_chdir - /home/noda/work/iss/Cassia/GitHub/noda50/oacis/public/Result_development/5a44b5ad9d409b71327ea4bb/5a44b6b09d409b71327ea50b/5a44b6b09d409b71327ea5c8

`
def result_paths( pattern = '*' )
    paths = nil
    Dir.chdir(dir) {
      paths = Dir.glob(pattern).map {|x| Pathname.new(x).expand_path }
    }
    # remove directories of Analysis
`

![_2017-12-28_21-13-47](https://user-images.githubusercontent.com/5162624/34410480-08be1d0a-ec14-11e7-8c16-3921ca299928.png)

**Comment by yohm** [comment]
該当するRunが存在していないということはないでしょうか？例えば、他のタブでそのRunか親のParameterSetを削除しているとか。

**Comment by yohm** [comment]
↑の件ですが、Runがすでに削除されているということは無さそうですね。Runがなければ別の例外が出るはずなので。

初めてみるエラーで、原因がわかりません:disappointed:
`public/Result_development/#{simulator_id}/#{parameter_set_id}/#{run_id}`のパスに結果が格納されるのですが、そのディレクトリが無いというエラーですね。Runを作ると同時にこのディレクトリも作成されるはずなのですが...

**Comment by noda50** [comment]
原因がなんとなくわかりました。
テストのため、oacis をストップしたりいろいろしているうちに、おかしくなった模様。
サーバ側と計算ノード側で、run の整合性がとれなくなったのか、そのあたり。

通常なら出ないのかもしれない。

**Comment by yohm** [comment]
また同じ問題が出たら状況を教えてください。とりあえずこのissueはcloseしておきますが、問題が再発する場合は再度openします。
