### ISSUE TITLE
bin/check_oacis_env checks Ruby's version incorrectly

### ISSUE THREAD

**Issue by naoki-yoshioka** [crest-cassia/oacis#551]
[OACISのドキュメント](http://crest-cassia.github.io/oacis/ja/install.html)によると、OACIS v.2.12.0以降はRuby 2.4以降に対応しているとあり、実際OACIS v2.13.2がRuby 2.5.0で正常に動作している（はず）ということは確認しています。

にもかかわらず、`bin/check_oacis_env`内には関数`verify_ruby_version`が残っていて、これを実行するとエラーが出ます。

**Comment by yohm** [comment]
ありがとうございます。
#553 で修正しました。
