### ISSUE TITLE
Web hook UI for OACIS watcher

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/oacis#646]
# New feature implementation
Getting a message form OACIS via web hook is hopeful.
There are several messaging cases and some of them are listed below.
1. When all jobs in a list become finished or failed, a report should be sent. (call OACIS watcher)
2. When the remaining disk space is less than 10%, a warn message should be sent.(call JobObserver.is_enough_disk_space_left?)
3. When a Host is unavailable, a warn message should be sent.(pending)

## Idea for implementation
1. cteate a new class (EventHandler)
    - It has a model in which event triggers, web hook parameters, logs and an always (with interval)/n times/disable status are defined.
    - It has a view to show on OACIS WebUI on the next of Simulators, Runs, Analyses, Hosts(, EventHanders).
    - It has a controller to create, update and delete an event.

**Comment by takeshi-uchitane** [comment]
@yohm 
curlとOACIS watcherを使えばなんとかなるのですが，せっかくなのでWebUIから叩けるようにしたいと思います．
Web hookにするのがいいのか，任意のスクリプト実行にしてcurlのサンプルつけるのがいいのか迷っています．
アドバイスあればよろしくお願いします．

**Comment by yohm** [comment]
@takeshi-uchitane OACISの標準機能として実装したいですね。
一般の webhook を作るのか、連携先となるアプリを限定して作るのか方法があるかと思います。
僕としてはslackとのintegrationを作りさえすれば十分なのかなと思いますがいかがですか？
slackのincoming webhooksを使って連携することを想定して、

- OACISのweb UI上でslackのincoming

**Comment by takeshi-uchitane** [comment]
@yohm 
> 連携先となるアプリを限定して作る
> slackとのintegrationを作りさえすれば十分

手間は削減できたほうがありがたいのでslackに限定するのに賛成です．

> 送信するイベントの種類をチェックボックスで選べる

最近利用したアプリでは，slackのchannnelをメッセージの種類ごとに選択できるようになっていました．
イベント種類ごとに，送り先URL登録，チャンネル登録，メッセージヘッダー編集ができるようにしたいと思います．

**Comment by yohm** [comment]
> 最近利用したアプリでは，slackのchannelをメッセージの種類ごとに選択できるようになっていました．
> イベント種類ごとに，送り先URL登録，チャンネル登録，メッセージヘッダー編集ができるようにしたいと思います．

ちょっと機能が多いですね。。。第一ステップとして送り先URLとチャネルだけでもいいかもしれませんね。メッセージは固定で。

**Comment by yohm** [comment]
#712 で対応予定のため、本issueはcloseする。
