### ISSUE TITLE
Observer is dead by an error of Net::SSH::ConnectionTimeout

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/oacis#647]
# What's happen

- Version: v3.6.2 , Access Level: 2
- logs
observer | 2019-11-22 10:19:49 +0000 | FATAL | undefined method `force_encoding' for #<Array:0x00005568a2b8e330>
-- | -- | -- | --
observer | 2019-11-22 10:19:49 +0000 | ERROR | Error in JobObserver: #<Net::SSH::ConnectionTimeout: timeout waiting for next packet>

- observer runs with no problem after restarting oacis

# Expected

- observer can be restarted automatically when it gets the error.

**Comment by yohm** [comment]
まずはsourceレベルで何が起きているのかを調べてみます

**Comment by takeshi-uchitane** [comment]
@yohm  すいません．急ぎだったので修正案作りました．
確認願います． #649

**Comment by takeshi-uchitane** [comment]
SSHのエラーはハンドルできていると思いますが，force_encodingが見当たらないというエラーは残ったままです．
しばらく様子見します．

**Comment by takeshi-uchitane** [comment]
急がせてすいません．
begin rescueを１ブロック外まで拡張したのですが，結局`undefined method `force_encoding' for #Array:0x00005568a2b8e330`のエラーでこけました．
`logger.error(ex.backtrace)`のところで`ex.backtrace.to_s`として様子を見ています．

**Comment by yohm** [comment]
> begin rescueを１ブロック外まで拡張したのですが，結局undefined method force_encoding' for #Array:0x00005568a2b8e330のエラーでこけました．

ですよね。PRの修正案で修正できる理由がわかりませんでした。
mosikasitara #640 が何か関連しているかもしれません。
