### ISSUE TITLE
Jobs での all select の挙動

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#653]
Jobs のところで、Finished Runs のタブを開けている時に、Runs をすべて選ぶためのチェックマーク（"RunID" というラベルの左） が機能しない。

Unfinished Runs のタブの方は機能していて、そこをチェックした後、タブを Finished Runs にすると、すべての Run が選択されている。

多分、バグ？

**Comment by yohm** [comment]
バグですね。調査してみます。

**Comment by yohm** [comment]
#713 で修正予定のため、本issueはcloseする。
