### ISSUE TITLE
incremental に PS を作ったときの plot

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#654]
Watcher で、incremental に PS を作ったとき、その PS の１つを選んで plot タブのところで plot しても、その PS に属する run しかプロットされない。

通常の、網羅的なパラメータセット自動生成の時は、その塊全部を表示していたように思うが、おなじように、すでにある run の結果を plot できないか？

**Comment by yohm** [comment]
@noda50 watcherで作ろうがUIで作ろうが中でやっていることは同じなのでPSのplotは同じようにできるはずなのですが、おかしいですね。。。
もしかしたら、プロットするときの軸以外のパラメータが微妙に違っていたりしないでしょうか？

考えられる原因としては、Floatのパラメータの違いかもしれません。UIで作った場合とAPIで作った場合とで微妙に丸め誤差が発生しているのかもしれません。
PS一覧のところに"Export CSV"というボタンがありますので、そこで軸に指定した以外のパラメータの値が全く同じ値になっているか確認してもらえないでしょうか？

**Comment by noda50** [comment]
あれ、もしかして、関係ない変数を mask するとよい？

**Comment by noda50** [comment]
お、できた。ありがとう。
