### ISSUE TITLE
Host に nickname の導入

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#656]
Host の登録において、現状では、その登録名と hostname (ssh する時に使うもの）が同一の扱いになっているが、これを分けたい。

例えば、同じホストで、異なる並列度などで試したいといったことができるようにしたい。

現状でも、.ssh/config あたりに同じホストで違う名前のものを作ることはできるが、OACIS のために .ssh/config をいじるのもおかしいし、避けたい。

**Comment by yohm** [comment]
@noda50 ご提案ありがとうございます。今のところnicknameを導入するのは避けようと考えています。.ssh/configで同じホスト違う名前のものを作ってもらうことでご対応いただきたいと思います。

> 現状でも、.ssh/config あたりに同じホストで違う名前のものを作ることはできるが、OACIS のために .ssh/config をいじるのもおかしいし、避けたい。

システムのファイルではなく、あくまでユーザー管理下にあるファイルを編集するだけなのでそれほどおかしいことではないと考えています。
ちなみに以下のように書くと、一つの設定を複数のホスト名で共有できます。

```
Host myhost1 myhost2
 HostName myhost.example.com
 ....
```

`?`や`*`などのワイルドカードも使えます。

> 例えば、同じホストで、異なる並列度などで試したいといったことができるようにしたい。

上記の方法でも起きる問題なのですが、例えばhostA, hostBが実は同一のホストだったときに、hostA,hostBそれぞれで指定されたジョブの最大数の和まで投入されることになりますが大丈夫ですか？
もし並列度だけ変えたい場合は、Hostの設定で、`support_mpi`のフィールドにチェックを入れると、ジョブ作成時にMPIの並列数を入力することができるようになります。つまりジョブ毎に並列数を指定することができるようになります。こちらの設定も検討してみてください。

**Comment by noda50** [comment]
@yohm 私はどちらかというと、 .ssh/config のお世話になるのは避けたい。
.ssh/config はあくまでその ssh がらみのリモート情報を集約すべきで、そこに Oacis の実験設定を波及させたくない。config に、同一ホストなのに別名を定義している理由が、その config に明示的に表すことができない。（あくまで Oacis の都合なので）

それと、Oacis で間違えて同じホストに並列度以上のジョブを投げる件ですが、.ssh/config に書くほうがよけいに間違いそうに思います。 Oacis のなかで記載するほうが、確認が取りやすい。（頑張れば、Oacis で重複チェックして、ワーニングを出すこともできる。そこまで親切設計するかどうかは、余力次第ですが。）

**Comment by yohm** [comment]
nickname をつけるくらいはしてもいいかもしれませんね。とりあえずconfigで同等のことができますので優先度は低めで対応します。

ところで、そもそもの問題になるのですが、どのように設定を切り替えているのですか？sshの設定が全く同じだと設定の切り替えをする方法が想像がつかなくて。
（ひょっとしてOACIS上での表示名だけ切り替わればいい？）


>  Oacis のなかで記載するほうが、確認が取りやすい。（頑張れば、Oacis で重複チェックして、ワーニングを出すこともできる。そこまで親切設計するかどうかは、余力次第ですが。）

重複チェックしてワーニング出すということは不可能ではないですが、申し訳ないですがやるつもりはないです。複雑さが増してしまいますので。

**Comment by noda50** [comment]
いま、直面している問題としては、同じマシンに対して、並列実行度（同時投げられるジョブの上限値）を切り替えて実験したい。
現状はいちいち、host の定義を web 上で書き換えながらやっている。
なんどもやっていると、いろいろ間違いが起きる（変更する忘れて走らせてたりなど）。

並列ジョブ上限を変更したい理由は以下の通り。

   * 異なる並列度でのパフォーマンスを調べたい時。
   * なげるジョブの重さや中身（使うメモリ量とかマルチスレッドを使うかなど）によって、並列度を変更したい時。

**Comment by yohm** [comment]
だんだんと状況がわかってきました。つまり、ジョブスケジューラ（Torqueなど）を使わずに手元のワークステーションにジョブを投げている状況ですね。並列度といっているのは、MPIなどの並列プログラムをさしているのではなくて、あくまでシリアル（もしくはマルチスレッドシングルプロセス？）の独立なジョブを同時に何本投げるか、というわけですね。

私が理解した限りは、hostのnicknameをつけるかどうかというよりは、Runの作成時に簡単に同時ジョブ投入数を制限できるようにしてほしい、というのが本当に解決したい問題だと理解しました。
現状のOACISでできる解決法としては以下の２つになります。

1. （正統な方法）ジョブスケジューラを導入する。Runの作成時にスレッド数やメモリ上限を入力することができるようになるので、適切にスレッド数や必要となるメモリを入力する。ジョブ本数はスケジューラによって管理される。
2. （上記の方法で手間がかかるからアドホックに処理したい場合）ご提案のとおりHostを複数（例えばhost1,host2）登録しておいてRunの作成時にどちらかを選ぶようにする。ただし、host1に投げたときにhost2に他のジョブが流れていないかどうかは自分でその都度確認する。

2をやるためにnicknameがほしいということですね。

**Comment by noda50** [comment]
実は、現在すすめている abci の使い方も、ワークステーションに投げるのに似ているので、そういう使い方をしている。

abci の場合、インタラクティブノードで、xsub (中で qsub になる) を大量に投げる形式。このxsub を大量に投げて並列実行させようとしている。なので、xsub 自体はスケジュラーになっていない（単にジョブを計算ノードに投げるだけ）

そうなると、その xsub をどんだけ並列で投げるか、になるので、並列度は xsub の外側の話になる。なので、上記のような話になっている。

**Comment by yohm** [comment]
そういうことであれば"~/.ssh/config"に書くことで対応していただけますか？nicknameを導入するとなれば丸１日仕事になりますが、configには数文字書くだけで対応できますので。

**Comment by noda50** [comment]
優先度は低くて構わないのですが、OACIS 側で対応したほうがいいと考えている。
というのは、このABCIの使い方、GA みたいな使い方と相性がよい。
また、おそらく、富嶽あたりも、ABCIを参考にした運用を考えると思うので。

なお、ABCI は、現在、後継の話も出ていて、 ABCI2 が多分できる。
つまり、似た構成の HPC が今後増えるので、OACIS機能としてあったほうがいいと感じてる。

**Comment by yohm** [comment]
「ABCIの使い方というのが」まだよくわかっていません。jupyter notebookのようなものが動かせるinteractive nodeという理解でいいのでしょうか？
一方で実際のジョブのキューイングにはqsubを使うんですよね？それならそちらでジョブ投入数の管理はされているような気もするのですが。

**Comment by noda50** [comment]
なかなかf2fでないと、伝わりにくいかな。

図としては、以下の通り。 qsub で管理されているのだけれど、並列ジョブの上限が、システムで決められている 200 並列に固定なので。（ちょっと前までは、制限もなかった）
なので、実用上、並列性は手元(OACIS)で管理しないといけない。

![figure-7](https://user-images.githubusercontent.com/5162624/71353362-1daa4980-25bc-11ea-804d-1fa89d817098.png)

**Comment by yohm** [comment]
口頭でもお伝えした通り、ABCIなどの運用状況を考慮してもnickname導入する重要度は高くないと考えています。とりあえずこのissueはcloseさせてもらいます。
