### ISSUE TITLE
Job から ParameterSet へ飛ぶリンクが欲しい

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#657]
Job の画面の、Run が並んでいるところから、各 Run のもとになっている ParameterSet へ飛ぶリンクが欲しい。

あと、ParameterSet の略称が、PS だったり Param だったりするのが、ちょっとわかりにくい。ドキュメントのサンプルプログラムなどでは PS や ps を使っており、Web の画面などでは、 Param を使っている。両者は同一の概念なので、同一名で扱うべき。

**Comment by yohm** [comment]
@noda50 確かに欲しいですね。何ができるか検討してみます。

用語の統一も必要ですね。"Param"があるのは、画面上部のパンくずリストだけだと認識していますが他にありますか？
![image](https://user-images.githubusercontent.com/718731/70872160-59a44400-1fe9-11ea-9785-91671f40d07e.png)

**Comment by noda50** [comment]
Jobs のページの、Run のテーブルで、Run の ID がならんでいる、その隣に、ParameterSet の ID を並べては？

**Comment by yohm** [comment]
> Jobs のページの、Run のテーブルで、Run の ID がならんでいる、その隣に、ParameterSet の ID を並べては？

そうしましょう。今、ParameterSetのページで表示しているRunの一覧テーブルと、Jobsのページで表示しているテーブルを共通化しているのですが、それぞれに特化したテーブルを作る方が良さそうですね。

**Comment by noda50** [comment]
あと、用語の統一としては、Run と Job の関係・区別がよくわからない。

**Comment by yohm** [comment]
Jobには、RunだけでなくAnalysisを含めた意味で使っています。

**Comment by noda50** [comment]
そうか。そういう命名なら、仕方ないか。

**Comment by yohm** [comment]
#714 で修正予定のためcloseする
