### ISSUE TITLE
show/hide columnsメニューに最後のパラメータが表示されない

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/oacis#658]
# Bug
パラメータセット一覧ページのshow/hide columnsで登録されているパラメータの最後の項目が表示されない

**Comment by yohm** [comment]
@takeshi-uchitane デバッグおねがい

**Comment by noda50** [comment]
関連しているかもしれないが、同じところの download CSV でも、最期の result が取得できていない気がする。

**Comment by yohm** [comment]
> 関連しているかもしれないが、同じところの download CSV でも、最期の result が取得できていない気がする。

これは全く違うバグの可能性が高いです。「最後」というのは、具体的には最後のRunのことですか？

**Comment by noda50** [comment]
そうではなくて、最後のカラムがないように思う。結果(_output.json）の中身の1項目が抜けている気がする。
