### ISSUE TITLE
Simulator 画面の Export CSV 機能の違和感

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#659]
Simulator 画面 (Simulators で１つの Simulator を選んだところ）の、Parameter Sets タブにある、"Export CSV" のボタンの機能が、名前・場所にそぐわない気がする。

この場所で Export CSV とあると、当然、Parameter Sets の CSV と類推されるが、実際にこの機能は、 Runs の CSV を出力する。

また、その CSV には、"_id" という欄があるが、これが、Run の ID なのか、 Parameter Sets の ID なのかわからない。（後に PS id があるので、そこまで見れば気づくのだが）

なので、

  * ボタンの名前を、 "Export Runs CSV" とする。
  * CSV の先頭欄のラベルを、"_id" ではなく "Run_id" とする。

としてほしい。

**Comment by noda50** [comment]
あと、1つの Simulation に関係する runs のみを表示するところがほしい。

例えば、 Parameter Sets の並びで、 Runs というタブを作り、そこに表形式で（Jobs のような形で）表示するなど。

Jobs の方は、複数のSimulatorの実験をやっていると、混在して表示されるので、見づらくなる。
（複数のSimulator実験するときには、Oacis 複数立てろ、というのもありだが、docker でも意外と立ち上げがめんどくさい。）

**Comment by noda50** [comment]
更に欲をいうと、 Simulator の画面の Progress のところで、finished, failed, running, submitted, created の数が表示されているところ、そのあたりをクリックすると、それに対応する run の表示に飛べる機能がほしい。

例えば、大量に run を走らせていて、failed になる例が少数ある時、原因究明のために、その failed の情報だけを参照したいが、今だと、膨大な jobs や parameter sets から見つけ出さないといけない。

**Comment by yohm** [comment]
> ボタンの名前を、 "Export Runs CSV" とする。
> CSV の先頭欄のラベルを、"_id" ではなく "Run_id" とする。

その方が良さそうですね。やります。

> あと、1つの Simulation に関係する runs のみを表示するところがほしい。

確かにこれはあると便利そうですね。表示が重くならないか確認しながらになりますが、実装したいと思います。

> 例えば、大量に run を走らせていて、failed になる例が少数ある時、原因究明のために、その failed の情報だけを参照したいが、今だと、膨大な jobs や parameter sets から見つけ出さないといけない。

確かにそういうユースケースはありそうですね。progressでクリックするのでもいいですが、上記のRunのテーブルが導入されたらstatusでソートすることによって解決できそうです。こちらの方が実装もシンプルになるので、Run一覧の導入を検討します。

**Comment by yohm** [comment]
Runのテーブルについては #671 のissueを作成しましたので、こちらのissueはクローズします。
