### ISSUE TITLE
実行結果の directory 表示

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#660]
Run の画面で、実行結果の directory を表示しているところ、階層に制限を設けているようだが、この制限、必要？

oacis が動作しているところの Result_development には、ちゃんと残っているようだが、web 画面上では、深い directory 構造の下のファイルは存在しないように見える。

**Comment by yohm** [comment]
これはパフォーマンス上の懸念があってこうしました。でも、開発の初期に判断した結果なので今なら問題がないかもしれません。制限を撤廃する方向で対応しようと思います。

**Comment by noda50** [comment]
了解。

制限するばあい、「制限されている」という情報が、どこかにあったほうがいい気がする。

しばらく、「なぜこの下にファイルがないのだろう。（自分の作った）スクリプトのばぐか？」と悩んでいたので。
