### ISSUE TITLE
Oacis の状態の Dump/Restore 機能

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#661]
Oacis の全状態、あるいは、Simulation ごととか、Host のリストの状態などを Save/Dump, Load/Restore できる機能がほしい。

Oacis の引っ越しをしたい、とか、そういう時に便利/必須。

＃テストで動かしていたマシンが非力で、増強のため引っ越したいなぁ、と感じたので。

**Comment by yohm** [comment]
バックアップレストアの手順はこちらにあります。
http://crest-cassia.github.io/oacis/ja/tips.html

**Comment by noda50** [comment]
おっと、すでにあったか。流石に、UI では面倒か。
