### ISSUE TITLE
User による Tips あるいは FAQ ページ

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#676]
User の経験によるトラブルシューティングなどを集めておくページがあると良いのではないか？

例えば、今回、いろいろ試行錯誤したのが、クラスタマシンを計算ホストとした時の設定。
よくある構成のクラスタは、
* マルチコアなノードを多数、独立したローカルネットでつなげる。
* そのうち１台（フロントエンド）だけがその外側のネットに繋がっている。
* 外からフロントエンドでないノード（計算ノード）に繋がるためには、フロントエンドを踏み台にして ssh するなどしないといけない。
* その場合、通常は、  `ssh -W <計算ノード>:22 <フロントエンド>` のような感じにする。
* しかし、これを多用すると、フロントエンドで ssh の接続数の上限に引っかかる。（通常、20程度）
* これを回避する方法として、フロントエンドに ssh する際に、 ssh を port-forwarding するトンネルを各計算ノード毎に開けてしまう、という方法がある。これをやれば、フロントエンドでの接続数上限の問題を軽減することができる。（現状で数百はOK）

こんな感じのノウハウ集を、気軽にアップして集約する場所があるといいように思う。

**Comment by noda50** [comment]
なお、ssh の接続数の上限を上げる、という解決策もあるが、これはいろんなところの制約が重なっていて、どういう設定が正解かよくわからない。わかっているのは、
* /etc/ssh/sshd.conf で、MaxSessions と  MaxStartups を大きな値にしておく。
* /etc/security/limits あたりで、ソケット、tty などの上限を緩めておく。
など。コレ以外にもあるのかもしれない。

**Comment by noda50** [comment]
上記以外の tips として、host の登録をした後、xsub の設定の間違いに気がついて修正すると、その host の設定で、一度 "Edit" をクリックした後、そのまま "Save" するとよい、など。
これは、xsub の設定を変更 (scheduler を変更するなど) すると、渡される引数が異なってくる。現状の xsub はそこをまじめにチェックしている。そこでエラーで弾かれるのは良いが、そのエラーが、「xsub の設定を変更したことによるエラー」であることが非常にわかりづらい。
かといって、こういうことに親切に対応できるエラーメッセージを用意して行くのはかなりの時間と手間がかかる。それを補うものとして、こういう tips をどんどん集積できると良いと思う。

**Comment by yohm** [comment]
まったくもって同感です。こういうページがあると助かりますね。我々としては、具体的に何ができるでしょう？
このgithubリポジトリのwikiページとかを公開するのも良いかもしれませんが、ここの情報はできればメンテナンスされた情報だけを載せたいと考えています。
Qiitaやブログとかに書いてもらうのが検索エンジンに引っかかりやすくてよいかもしれません。

**Comment by yohm** [comment]
@noda50 このあたり手始めにqiitaに上げてもらえませんか？
https://qiita.com/yohm/items/a3dc247713ae1f409ec8 こんな具合に`oacis`のタグをつけてもらえるとわかりやすいと思います。
