### ISSUE TITLE
長い文字列の parameter を受け付けない。

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#679]
string で型づけした parameter の値として、長い文字列を与えると、mongo DB の index が作れないというエラーで落ちてしまう。
以下、エラーの画面ダンプとテキスト。

![スクリーンショット_2020-02-02_04-45-16](https://user-images.githubusercontent.com/5162624/73598076-e8a7f400-4576-11ea-96ea-88caff9ccc4f.png)

> Mongo::Error::OperationFailure in ParameterSetsController#create
>WiredTigerIndex::insert: key too large to index, failing 1601 { : ObjectId('5e35d1540d14d83e6b3da870'), : { corpList: ""[{\"class\":\"SavServiceCorp\",\"name\":\"corp000471\",\"savN\":10,\"allocatorConf\":{\"type\":\"seqOpt\"},\"price\":{\"constant\":300,\"distance\":1..." } } (17280) (on 127.0.0.1:27017, legacy retry, attempt 1) (on 127.0.0.1:27017, legacy retry, attempt 1)

>Extracted source (around line #40):
          v = Hash[definitions.zip(param_values).map {\|defn, v\| [defn.key, v]}] 
          ps = simulator.parameter_sets.find_or_initialize_by(v: v)
           created << ps if ps.persisted? or ps.save
       else
           break
       end

>Rails.root: /home/noda/work/iss/Cassia/GitHub/noda50/oacis
Application Trace | Framework Trace | Full Trace
app/models/save_task.rb:40:in `block in make_ps_in_batches'
app/models/save_task.rb:34:in `each'
app/models/save_task.rb:34:in `each_with_index'
app/models/save_task.rb:34:in `make_ps_in_batches'
app/controllers/parameter_sets_controller.rb:69:in `create'

>Request
Parameters:
{"authenticity_token"=>"ph88shxgKzYm9JXc8X9rhFX5IfdtSK3EWk6txBXPVnRkd7hgzilpcLR4pRvRvk1A4p4YNrojONP2bEa+OFq4Hg==",
 "v"=>
  {"corpList"=>
    "\"[{\\\"class\\\":\\\"SavServiceCorp\\\",\\\"name\\\":\\\"corp000471\\\",\\\"savN\\\":10,\\\"allocatorConf\\\":{\\\"type\\\":\\\"seqOpt\\\"},\\\"price\\\":{\\\"constant\\\":300,\\\"distance\\\":1.110217557642492,\\\"delay\\\":0.34461762854603106,\\\"lowerBound\\\":\\\"constant\\\"},\\\"totalIncome\\\":6692093.648769074,\\\"totalIncomeConf\\\":3676833.972873789,\\\"totalSqIncome\\\":3652109614846.7217,\\\"expN\\\":29,\\\"totalCount\\\":1754,\\\"totalSqCount\\\":318868,\\\"totalCancel\\\":188,\\\"totalSqCancel\\\":17120,\\\"totalRepute\\\":-24.34785005344224,\\\"totalSqRepute\\\":21.25615956986831,\\\"partyN\\\":29},{\\\"class\\\":\\\"SavServiceCorp\\\",\\\"name\\\":\\\"corp000090\\\",\\\"savN\\\":10,\\\"allocatorConf\\\":{\\\"type\\\":\\\"seqOpt\\\"},\\\"price\\\":{\\\"constant\\\":300,\\\"distance\\\":3.971293353230624,\\\"delay\\\":0.7882889135837269,\\\"lowerBound\\\":\\\"constant\\\"},\\\"totalIncome\\\":12237596.605266148,\\\"totalIncomeConf\\\":1716231.9244583363,\\\"totalSqIncome\\\":5333419045365.992,\\\"expN\\\":30,\\\"totalCount\\\":781,\\\"totalSqCount\\\":21269,\\\"totalCancel\\\":2,\\\"totalSqCancel\\\":2,\\\"totalRepute\\\":-120.74462936350547,\\\"totalSqRepute\\\":487.7813985042642,\\\"partyN\\\":30},{\\\"class\\\":\\\"SavServiceCorp\\\",\\\"name\\\":\\\"corp000254\\\",\\\"savN\\\":10,\\\"allocatorConf\\\":{\\\"type\\\":\\\"seqOpt\\\"},\\\"price\\\":{\\\"constant\\\":300,\\\"distance\\\":0.07371841380421217,\\\"delay\\\":1.5735322887704857,\\\"lowerBound\\\":\\\"constant\\\"},\\\"totalIncome\\\":2068452.5105446076,\\\"totalIncomeConf\\\":1800140.0053710958,\\\"totalSqIncome\\\":146324100383.63004,\\\"expN\\\":30,\\\"totalCount\\\":7869,\\\"totalSqCount\\\":2139277,\\\"totalCancel\\\":474,\\\"totalSqCancel\\\":40738,\\\"totalRepute\\\":-0.27444028402460097,\\\"totalSqRepute\\\":1.4091539946931415,\\\"partyN\\\":30}]\""},
 "num_runs"=>"1",
 "run"=>{"submitted_to"=>"5e35a0520d14d83e6b3da7c0", "priority"=>"1"},
 "commit"=>"Create",
 "simulator_id"=>"5e35d1540d14d83e6b3da870"}

**Comment by noda50** [comment]
現状だと、引数に階層構造をもたせられない。なので、階層構造を表す JSON 文字列にして渡そうとしている。
文字列長に上限があると、階層構造に限界が出てきてしまい、自由度がかなり制限される。

**Comment by noda50** [comment]
以下のサイトによると、1024 byte 以上は index 作れないが、text index とか hashed index とかいうのがあるらしい。 string 型の parameter をそちらに切り替えられないか？

https://stackoverflow.com/questions/27792706/cannot-create-index-in-mongodb-key-too-large-to-index

>MongoDB will not create an index on a collection if the index entry for an existing document exceeds the index key limit (1024 bytes). You can however create a hashed index or text index instead:
>
db.logcollection.createIndex({"Module":"hashed"})

**Comment by yohm** [comment]
1024byte以上の文字列パラメータは特殊ケースで、上記のページにもあるようにパフォーマンス上の懸念もありますのでhashed indexを導入することは控えたいと思います。
Simulatorを導入する際に、パラメータとして生のJSONをそのまま渡すのではなく、変える可能性がある部分のみの最小化した文字列を渡すようにしてはどうでしょうか？

**Comment by noda50** [comment]
実は、特殊ケースにならなくなってきている。

エージェントシミュレーションで、エージェントの行動とかを GA や GP で最適化するようなことをやっていると、エージェントの行動設定自体が構造を持つようになるので、構造を含めて設定項目数が可変になる。さらに、エージェント毎に別々の設定を与えるなどするので、別々のパラメータとすることも現実的でない（例えば、１００種類与えるなど）

ただし、そういう設定の場合は、同一性を気にしない（まず同じ設定にならない）ので、 index でチェックする必要がない。

よって、以下のようなことはできないか？

- index をつけない、長さ無制限の string 型パラメータを許す。これについては、同一性チェックは行わない。あるいは、別途、hash 値をつけて、それで同一性管理。

- 同じことだが、json 型というのを用意して、長さ無制限で、かつ、index をつけないものを用意する。この場合、DBへの格納は、json 文字列とするが、_input.json に出す際には、その文字列を一度 json として解釈した後の結果を出力する。

**Comment by yohm** [comment]
json型というアイデアは良さそうですね。MongoDBとも相性が良さそうです。
その場合おっしゃる通りindexを貼る意味は無さそうなので、indexを貼らない実装にする必要がありますね。
今考えている範囲だととても良い仕様だと思います。どういう懸念点がありうるかしばらく検討させてください。

**Comment by noda50** [comment]
懸念があるとすると、 json 型と int 型が組になった parameter set があった時、int 型が同じだが、json型が違う場合に、それを、「同じ設定」とみなすかどうか。

上記の使い方では、「同じとはしない」にしたい。つまり、json 型があると、かならず違うものとみなしてほしい。

別の方法としては、json がたがあると、その文字列の finger print を求めて、それを index されるデータとして補助的に入れる。で、同値性判定では、まずその finger print の一致性をみて、一致したら、json 文字列自体を比較する。一致しない文字列の finger print がぶつかる確率は非常に小さいので、一致性チェックとしては問題ない程度の速さのはず。

**Comment by noda50** [comment]
ここで言っている finger print は、sha512 などの hash のつもり。
ruby なら、Digest::SHA512 とかのクラスがある。

**Comment by yohm** [comment]
> ここで言っている finger print は、sha512 などの hash のつもり。
> ruby なら、Digest::SHA512 とかのクラスがある。

これがまさにmongodbのhashed indexがやっていることだと思います。もちろんrubyでも実現できますが、そういうハックを繰り返していくとメンテナンス性を犠牲にするのでできるだけ標準的な機能で実現するにはどうすればよいか考えています。

また、この問題ですが調査した結果どうやら単純にindexの問題ではないかもしれません。実はParameterSetのコードを確認したら、そもそもパラメータの値はindexしていませんでした。でも、なぜかmongodbからはindexが長すぎるというエラーが返ってきていて、なんでだろう？と思っているところです。

**Comment by noda50** [comment]
エラーメッセージは、Index でオーバーしてる、と出てるんだけどなぁ。

それと、MySQL とかだと、text は通常、長さの上限を指定するのですが、
mongo DB では、どうなってるんでしょう？

野田

=== [At Thu, 06 Feb 2020 16:29:14 -0800]

**Comment by yohm** [comment]
@noda50 

> また、この問題ですが調査した結果どうやら単純にindexの問題ではないかもしれません。実はParameterSetのコードを確認したら、そもそもパラメータの値はindexしていませんでした。

これは間違いでパラメータの値をindexしていました。

その上でパラメータに長い文字列を指定する方法がわかりました。Mongo DB 4.2ではindex長の上限が撤廃されていますので、長い文字列も指定できます。
https://docs.mongodb.com/manual/reference/limits/#Index-Key-Limit

MongoDBを更新する手順は公式のドキュメントをみてください。またFeature compatibility versionも4.2にする必要があり、以下の２つの手順を実行すればOKです。

- mongodb 4.2をインストール
- mongo shell上で `db.adminCommand( { setFeatureCompatibilityVersion: "4.2" } )` を実行

https://docs.mongodb.com/manual/reference/command/setFeatureCompatibilityVersion/#view-fcv

**Comment by noda50** [comment]
試してみます。
（うーん、報告書シーズンになって、時間がぁ、、、）
