### ISSUE TITLE
文字列中のカンマの扱い

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#680]
string 型のパラメータにおいて、カンマの扱いがトリッキー。

string で宣言しているパラメータの値に、カンマを含む文字列を与える方法がない。

カンマを含んだ文字列を、「"」で囲わずに与えると、カンマで区切られてしまう。
一方、「"」で囲うと、その「"」を含んだ文字列として扱ってしまう。

string 型の値は、もし「"」で始まる場合は、その「"」を文字列の delimiter として扱う、という扱いのほうが、統一性が取れると思われる。

**Comment by yohm** [comment]
ここは開発当初からどうするか迷った上で今の仕様にしているのですが、おっしゃる通りコンマをエスケープする方法がないんですよね。
今の仕様はJSONとして認識できる文字列はJSONとして一つの文字列として認識するという変な仕様になっています。`"`を区切り子として使うのも少しおかしいので、標準的なcsvの仕様にそって解釈するように変更するつもりです。

**Comment by noda50** [comment]
あれ、実際、この問題に気がついたのは、JSON 文字列だったのだが。
もしかして、配列型のJSONには対応していなかった？ (「 [ 」で始まる JSON）

**Comment by noda50** [comment]
別のところに書いたけど、string ではなく、json というデータ型を用意するのはどう？

**Comment by yohm** [comment]
JSON型は真剣に検討してみます。
それとは別に、文字列に","を渡せない問題はCSVの標準的な仕様に近い方式に修正しますね。

**Comment by yohm** [comment]
fixed by #689 #691
