### ISSUE TITLE
oacis_irb vs oacis_pry

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#681]
現在、oacis_irb は irb ではなく、pry を使って対話モードを実現しているが、これはあまり良くないかもしれない。

エラーが発生した時、irb は、ruby と同じくかなり深いエラースタックをちゃんと表示するが、pry は、そこを簡潔化してしまう。
一方、gem を使っていると、エラーの発生箇所からさらに潜ってエラーが発生してしまうことが起こりうる。

再現できる簡単なスクリプトはまだないが、未知の定数が現れると、gem はなにかをロードしようとして、最終的にエラーとなる。しかし、その最終的なエラーと、未知の定数を参照した箇所は、call stack ではかなりはなれている。pry は、最も浅い call stack しか表示しないので、実際、どこでそのバグの場所（未定義の定数を参照したところ）がわからない。

案としては、 oacis_irb と oacis_pry を別に設けるか、oacis_irb の引数で、irb で起動するか、 pry で起動するかを切り分ける。

**Comment by yohm** [comment]
なるほど、そんな違いがあるんですね。oacis_irbについては名前の通りirbを使うことにします。pryはどちらかと言えば開発者向けなので、今まで通り`bundle exec rails c`で使えばよいことにします。

未知の定数のときの挙動については、pry,irbの違いというよりはrailsの定数自動読み込みの仕組みが原因と思います。
