### ISSUE TITLE
run の状態表示とシンボリックリンク

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#683]
１つの run の directory にシンボリックリンクがあり、それが深い directory をもっていたり、あるいはかなり膨大なファイル群をその先にもっていたりすると、 run の表示が非常に重くなる。

これはおそらく、 run を表示する際に、directory 構造をシンポリックリンクを辿ってでも表示しようとするために思われる。

シンポリックリンクは辿らずに、その先の path だけ出す、というのではだめか？

**Comment by noda50** [comment]
この問題、やはりかなり深刻に思う。

worker 上で実行の環境を作る際、シンボリックリンクで関係するライブラリの path をローカルに持ってくることなどすると、かなり面倒なことになる。

今、こちらで直面しているのが、

1. worker の実行環境に、シミュレータの開発環境の root directory を symbolic link。
2. その開発環境からは、いろいろとテストのために、oacis の root directory を symbolic link。
3. oacis は、run が終了すると、実行環境を oacis のホスト側にコピーする。この段階では、symbolic link は symbolic link のまま。
4. oacis の run の状況を観るページを開こうとすると、oacis は、コピーされた実行環境の directory を表示しようとする。この際、symbolic link も辿って、実行環境以下をすべて表示しようとする。その際、画像はサムネイルを作るなどの作業もしている。
5. すると、oacis の root directory 以下にあるものも全部表示の準備処理が回ってしまう。
6. 結果、run の状況表示のページが異常に重くなり、また、表示されるまでかなり待たされる。下手をすると、その処理のためのプロセスが大量に溜まってしまう。

**Comment by noda50** [comment]
現状では、しかたないので、シミュレーションが終わると、実行環境に張ったsymbolic link を消すというプロセスを最後に入れることで回避している。シミュレーションがエラーで途中で落ちてもちゃんと消すようにしないといけないので、意外と面倒。（つまり、一般ユーザには対処が難しい）

**Comment by yohm** [comment]
symbolic linkを辿って欲しい人もいると思いますし、実際それを辿らないと「なんで表示できないんだ」と不思議に思う人も出ると思います。
これはファイル表示の階層を限定的にするという問題と似たような問題だと思います。

原則はあくまで「実行ディレクトリにあるものは結果ファイルとみなす」です。なのでsymbolic linkが表示されて困るのであればユーザーの責務で削除する、ということでお願いします。

**Comment by noda50** [comment]
じつは、そのせいでデバッグできない、という問題が生じている。
エラーが起きているのはわかるが、その詳細を確認できない。その原因が、このリンクをたどる、という機能。
でも、それに、おそらく普通の人は、気がつかない。
（表示に5分とかかかるので、そもそも OACIS がそうなっているとは、誰も思わない）

つまり、OACIS に起因するトラブルを、できるだけ割けないといけない、というのが、趣旨。

**Comment by noda50** [comment]
ポイントは、表示の際に、symbolic link を辿ったすべてを一気にブラウザ側に持ってこようとしているところ。
このために、web server, ブラウザ、両方に課題な負荷がかかり、表示ができない、というトラブルになっている。

**Comment by yohm** [comment]
symbolic linkを辿るかどうかというよりは、ディレクトリ階層ごとにファイルのリストをとってくればいいという話ですね。深い階層まで取ってくるようにしたのでこういうことも起きうるだろうなと思っていました。単にsymbolic linkを辿らないようにしても結局同じような問題が起きうると思います。

ディレクトリ階層ごとにリストを取得するのは技術的には可能ですし、やった方がよい課題だと思います。PRを送ってくれれば嬉しいです。
