### ISSUE TITLE
List of Simulator Versions の表示内容

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#684]
Simulator 画面の About のところに表示されている情報が、間違っているのではないか？
"Oldest started_at" と”Latest started_at" のところに表示されているのは、どういう情報なのか？
少なくとも、いかのスクリーンショットのように、Oldest より Latest の方が新しい時刻になっている。

![スクリーンショット_2020-02-16_17-33-52](https://user-images.githubusercontent.com/5162624/74601509-8a385500-50e2-11ea-9b4c-c4b878b2df46.png)

**Comment by noda50** [comment]
あっと、ちょっと勘違い。
時刻が間違っているのではなくて、 "XX h ago" のところがおかしい。

**Comment by yohm** [comment]
ご報告ありがとうございます。確認します。

**Comment by yohm** [comment]
タイムゾーンの問題とoacis上での表示の問題があるようです。
おそらくリモートマシンのタイムゾーンの影響か何かわかりませんが、９時間表示がずれていると思われます。たぶん"Latest_started_at"の時間が今から９時間「先」を示しているのではないかと推測します。リモートマシンまたはoacisのマシンの設定をご確認ください。
oacisでの表示の際はrailsの`distance_of_time_in_words_to_now`というメソッドで得られた文字列に" ago"という文字列を付けています。ここが未来の時刻になることは想定しないためです。通常は未来になることはないはずなので、これについては修正しません。

一方で別の問題として、localeによって`date`の表示が変わって正しく時刻をパースできない問題がありましたので修正しています。(#688)
