### ISSUE TITLE
ssh トンネル＋３００並列実行時に止まってしまう

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#690]
本件、再現性はあるけど、規模が大きくないと発生しない（確率が低い？）ので、とりあえず報告。
あと、これは OACIS の問題なのか、ssh や linux の OS の問題なのかは、まだ特定できていない。

以下のような環境・条件で大規模に実験していると、そのうち（１日くらいたって）、シミュレーション実行が止まってしまう。

- 合計で 300 コアあるクラスタ(ノード数は12)を計算ノードで使用。（300並列でシミュレーション実行）
- クラスタは、ある出島ノードで、OACISが動いているサーバと繋がっている。つまり、出島ノードを踏み台にして ssh しないといけない。
- 踏み台の方法としては、まず、手動で出島ノードにsshする。その際、クラスタの各ノードの ssh port へのトンネルを開けておく。つまり、１２本のトンネルを開ける。
- OACIS (および .ssh/config)の設定としては、12個の Host を登録し、各々、個別に開けたトンネルを使って ssh するようにしておく。
- OACIS では、さらに、HostGroup としてその12台をまとめておく。
- 1回の実行に10-20分くらいかかるシミュレーションを、OacisWatcher でsubmit していく。最終的に数万件くらいになる。（GAなので、実は無限に続く）

これをしかけると、最初の方は順調に進んでいく。並列度も、同時に300シミュレーション走っているのが確認できる。半日たっても、とくに問題に思える状態にはなっていない。しかし、1日くらいたつと、以下の状態になって、進まなくなっている。

- 計算ノード上では、シミュレーションのプロセスは走っていない。
- OACIS の方では、計算ノードで job が走っていることになっている。
- その状態が何時間も続いていることになっている。

なお、計算が終わっているものについては、ちゃんと結果が保存されている。
ディスク容量も特に足りてないことはない。

**Comment by noda50** [comment]
なお、なぜ、12本トンネルあける方法をとっているかの理由は、以下の通り。
- 単に、出島ノードを踏み台にして計算ノードに ssh ログインするような ssh/config 設定で行うと、300並列になるまえに、止まってしまう。どうも、同時に ssh で受けられる上限数が決まっている様子。単純な踏み台法だと、計算ノードに ssh ログインするたびに、出島ノードにも ssh ログインすることになる。このため、出島ノードに大量の（同時に300の）sshログインが発生し、その上限に達してしまう。
- トンネル法だと、出島ノードへのログインは1回で、計算ノードへのログインは、トンネルを通過して直接計算ノードに達するので、ssh ログインの上限にひっかからない。

**Comment by noda50** [comment]
この問題のリカバーは、OACISを再起動しないといけない（ように思われる）

**Comment by yohm** [comment]
まず確認させてほしいのは最新版のOACISですよね？
止まった時に`log/job_observer_worker.log`にログが出ていると思いますのでそれを確認してもらえますか？

**Comment by yohm** [comment]
実は以前あった #631 の問題に症状が似ています。想定していないレアケースがあるのかもしれません。

**Comment by noda50** [comment]
バージョンは、メイン画面で、
    Version: v3.7.1 , Access Level: 2
と出てます。
（いろいろ活用しているので、おいそれとアップデートできないのが悩みどころ :-p)

**Comment by noda50** [comment]
いま、ちょっと別の長大ジョブを流してしまったので、上記の問題を再度発生させるジョブを流すのは、来月になってしまうと思う。

**Comment by yohm** [comment]
最新版ですね。また問題の再発をまちましょう。
もし以前と同じ問題が発生しているならば、問題の箇所で処理が止まってしまうのでlogを見れば解決方法がわかると思います。

**Comment by noda50** [comment]
とりあえず、再度、長大ジョブを流してみています。
で、なんとなく詰まった状態になったので、 "Logs" というところを見てみています。

すると、以下のようなエラーが大量に発生しています。

>Worker: observer
Severity: ERROR
Message:
["/home/noda/work/iss/Cassia/GitHub/noda50/oacis/lib/ssh_util.rb:73:in `download_directory'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/lib/ssh_util.rb:82:in `download_recursive_if_exist'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/services/job_includer.rb:120:in `download_work_dir_if_exists'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/services/job_includer.rb:21:in `block in include_remote_job'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/models/host.rb:148:in `block in start_ssh_shell'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/models/host.rb:130:in `start_ssh'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/models/host.rb:146:in `start_ssh_shell'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/services/job_includer.rb:4:in `include_remote_job'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/job_observer.rb:88:in `observe_job'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/job_observer.rb:70:in `block in observe_jobs'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/contextual/mongo.rb:705:in `yield_document'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/contextual/mongo.rb:134:in `block in each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/collection/view/iterable.rb:51:in `block in each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/cursor.rb:154:in `block in each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/cursor.rb:152:in `loop'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/cursor.rb:152:in `each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/collection/view/iterable.rb:50:in `each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/query_cache.rb:227:in `each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/contextual/mongo.rb:133:in `each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/contextual.rb:20:in `each'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/job_observer.rb:68:in `observe_jobs'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/job_observer.rb:38:in `block in observe_host'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/models/host.rb:154:in `block (2 levels) in start_ssh_shell'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/lib/ssh_util.rb:32:in `block (3 levels) in start'"]

**Comment by noda50** [comment]
なお、上記のエラーの箇所（lib/ssh_util.rb:73) は以下の通り。

```
 def self.download_directory(hostname, remote_path, local_path)
    FileUtils.mkdir_p(local_path)
    cmd = "scp -Bqr '#{hostname}:#{remote_path}/*' #{local_path} 2> /dev/null"
    system(cmd)
    raise "'#{cmd}' failed : #{$?.to_i}" unless $?.to_i == 0
  end
```
この"raise"のところでエラーになっている。

**Comment by noda50** [comment]
"log/job_observer_worker.log" のサンプルはこんな感じ。
[job_observer_worker.log](https://github.com/crest-cassia/oacis/files/4277490/job_observer_worker.log)

**Comment by noda50** [comment]
ただ、よく見ると、まだ完全には止まってない。
（これまでの経験で3日目くらいに完全にとまる）
もう少し様子見ます。

**Comment by yohm** [comment]
共有ありがとうございます。これはまた別の問題みたいですね。
たぶんなんらかの事情でwork directoryが空になっていて、それをダウンロードしようとしてエラーになっているようです。これはこれで調査してみます。

**Comment by noda50** [comment]
エラーが生じている部分、work directory を再帰的に潜っていっているように見えるのだけれど、もし、remote 側の work directory の一部の symbolic link が切れている（symbolic link の宛先が存在していない) とどうなる？

実は、私がいろいろあげた問題の中で、work directory をまるごと持ってくる際、symbolic link をたどってしまって、膨大な量を持ってきてしまう、というのがあったと思う。
これを回避するために、シミュレーションで必要な directory を一時的に symbolic link し、さらにその symbolic link を参照していくつかの directory やファイルを symbolic link する、という操作をしている。そして、シミュレーションが終わった際に、最初の symbolic link を消すことで、補助的に張った残りの symbolic link を辿らせないようにしている。

上記のエラーの原因はもしかしてそれ？

**Comment by yohm** [comment]
おそらく関係ないと思います。symbolic linkの問題は表示の問題で、コピーするときの問題ではないです。

**Comment by noda50** [comment]
最初にIssueをあげた時の問題と同じかどうかわかりませんが、類似の状態になったので、報告。

状態としては、

- OACIS の方では、ジョブが走っていると思っている。（今回は、複数ある計算ノードのうち、ある1台にまかせたジョブ）（Issue にあげた際は、複数ある計算ノード（Host Group に登録されたもの）に投げた全てのジョブがそうなっていた）
- Logs の方には、”Net::SSH::AuthenticationFailed" のエラーが報告されている。（後ろに、ログ詳細）
- 当該計算ノードの方では、ジョブは全く走っていない。今回の場合は、何かの問題で、そのノードがリブートされてしまっていた（これの原因はまだ不明）。このリブートの際、/home の mount に失敗して、ssh が通らない状態になっていた。このため、上記の AuthenticationFail が生じていたと考えられる。再リブートして、/home のマウントを正常にすると、上記のエラーは生じなくなっている。
- 上記のエラーは生じないが、それでも、OACIS の方は job が走っていると思ったままになっている。なので、そのジョブを failed や 再度 submit せず、ひたすら待っている状態のように見える。
- Hosts の画面で、当該計算ノードを選択して、"Job Information" の "Check Scheduler Status" は、正常に（なにも走ってないのを）表示される。
- もともとの Issue をあげたときと、今回との違いは、OACIS Watcher を使ってジョブを投げるプロセスの重さ。そのプログラム自体は変わっていないが、プログラムの都合上、シミュレーションを積み重ねるに従って、ファイル入出力が重くなる（ある読み書きするファイルのサイズが単調増加で増える）ため、ジョブを投げる速度が徐々に落ちていくようになっている。このため、直近で投げた長大ジョブでは、ジョブを投げる速度がゆっくりになっていて、300並列に間に合ってない（300並列まで達しない。せいぜい150並列くらい）。それがどう関係しているかはまだ不明。

以下が、Logs に出ていた、関係しそうなエラー。（同様のが繰り返しでている。数秒おきにでているように見える。）

> ERROR	Error in JobObserver: #<Net::SSH::AuthenticationFailed: Authentication failed for user noda@localhost>

> ["/usr/local/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:263:in `start'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/models/host.rb:133:in `start_ssh'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/models/host.rb:146:in `start_ssh_shell'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/job_observer.rb:30:in `observe_host'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/job_observer.rb:15:in `block (2 levels) in perform'", "/usr/local/lib/ruby/2.6.0/benchmark.rb:293:in `measure'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/job_observer.rb:14:in `block in perform'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/contextual/mongo.rb:705:in `yield_document'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/contextual/mongo.rb:134:in `block in each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/collection/view/iterable.rb:51:in `block in each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/cursor.rb:154:in `block in each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/cursor.rb:152:in `loop'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/cursor.rb:152:in `each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongo-2.11.2/lib/mongo/collection/view/iterable.rb:50:in `each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/query_cache.rb:227:in `each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/contextual/mongo.rb:133:in `each'", "/usr/local/lib/ruby/gems/2.6.0/gems/mongoid-7.0.5/lib/mongoid/contextual.rb:20:in `each'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/job_observer.rb:9:in `perform'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/job_observer_worker.rb:11:in `block in <class:JobObserverWorker>'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/worker.rb:22:in `block (2 levels) in start'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/worker.rb:21:in `each'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/worker.rb:21:in `block in start'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/worker.rb:20:in `loop'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/app/workers/worker.rb:20:in `start'", "/usr/local/lib/ruby/gems/2.6.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:51:in `block in start'", "/usr/local/lib/ruby/gems/2.6.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:38:in `fork'", "/usr/local/lib/ruby/gems/2.6.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:38:in `start'", "/usr/local/lib/ruby/gems/2.6.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:181:in `block in start'", "/usr/local/lib/ruby/gems/2.6.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:181:in `map'", "/usr/local/lib/ruby/gems/2.6.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:181:in `start'", "/usr/local/lib/ruby/gems/2.6.0/gems/daemon-spawn-0.4.2/lib/daemon_spawn.rb:165:in `spawn!'", "/home/noda/work/iss/Cassia/GitHub/noda50/oacis/lib/tasks/boot_job_observer_worker.rb:2:in `<main>'"]

**Comment by noda50** [comment]
なお、上記の報告の中の、「リブートされた計算ノード」ですが、ログから、ネットワークの調子がよくなさそうな感じがする。ただ、messages を見ても、いきなり reboot からログが始まっているので、ハード的なトラブルに見える。

**Comment by noda50** [comment]
止まっていた計算ノードを再起動し、ちゃんと ssh でアクセスできるようにした所、"Jobs" の画面で、上部に、"Worker process exists, but may be hanging up" というメッセージが赤く表示された。

待っていても仕方ないので、止まっている job を選択して delete した所、"Simulator" の画面で、新しいジョブ（parameter sets) が生成（？）されて、同じ計算ノードに submit された。
で、この状態で、それらのジョブが、submitted から running に移行せずに止まっている。

さらに、別の計算ノード（トラブルを起こしていない計算ノード）に対して、新たな parameter set を投げてみても、 submitted から running に移行しない (failed にも移行しない)。

さらに、この実験で使っているシミュレータでない、非常に簡単なシミュレータ（単に、3つの数字を受け取って簡単な計算して返すだけのスクリプト）で、同様のことをしても、詰まってしまっている。

このことから、以下の不具合状況が考えられる。

- （計算ノードの不具合などで）ジョブの状況が確認できなくなると、ジョブの制御が詰まり始めるのではないか。つまり、確認できないジョブを処理できないと、新たなジョブを投げられなくなっていないか？

**Comment by noda50** [comment]
oacis を再起動すると、上記の詰りは解消しているように見える。（うまく実行されている）

**Comment by yohm** [comment]
問題解決のためにまずはoacisがどのように情報を更新しているか共有しようと思います。
まずoacisのworkerプロセスですが２種類あります。（本当は３種類ですが本件に関連するのは２種類です）

一つはjob_submitterと呼んでいるものです。これはジョブの投入を担うもので、runのstatusを`created`から`submitted`に変更します。
もう一つはjob_observerと呼んでいるもので、投入後のジョブの状態確認、結果の回収などを行います。`submitted`になっているジョブを`running`,`finished`,`failed`の状態に変更します。

今回の症状を見るとおそらくjob_submitterは生きているけど、job_observerが止まってしまっているものと思われます。なんでそうなってしまったのかがわからないのですが、job_observerが止まっている時に"log/job_observer_worker.log"というファイルの末尾を見ると何か情報がえられるかもしれません。
おそらく「ERRORという表示は出ていないがログの更新が止まっている」という状態になっているのではないかと思います。そのログの末尾部分を共有してもらえるとデバッグできるかもしれません。

**Comment by noda50** [comment]
#694 との関係で、もしかしたらこの不具合の原因がわかったかもしれない。

ポイントは、複数箇所で開発しているところ。rsync しているので、別々のマシンのある directory を完全に一致させようとする。Oacis を開発・動作させているところも、rsync する領域に入れている。このため、tmp とかに書かれている情報が変更され、データの整合性がずれてくる（いくつかのマシンではOACIS は絶えず動かしているので）。
このせいで、まず、Oacis の動作がおかしくなる。また、それの解消のためにOacis を立ち上げ直した時、submitter や observer がちゃんと死なないまま、次のが起動してしまう。(tmp の中が変わっているので、PIDとかおかしくなっているので、rake を正しく stop や restartすることができない。）

すくなくとも、本日、テスト用で failed になるはずのない単純な simulator でテストしている際、なぜか failed になる例がいくつか出てきていた。log を見ると、public/Result_development のある directory が見つからないとのメッセージ。で、ps などで詳細を調べると、異なる環境で動いている submitter や observer があるのを発見。

一応、上記のうち、おそらく古くから動いているであろう worker を kill して、様子を見ているところ。

**Comment by yohm** [comment]
> Oacis を開発・動作させているところも、rsync する領域に入れている。このため、tmp とかに書かれている情報が変更され、データの整合性がずれてくる（いくつかのマシンではOACIS は絶えず動かしているので）。

一つ目のoacisを起動しているまま（ファイルの書き出しとかダウンロードとか盛大にやっている最中に）、丸ごとコピーして同じ２つ目のoacisも起動するんですか？！なんでこんなことやってんですか...。これで不具合とか言われても困ります。せめてrsync前にoacisを一度止めてください。oacisを停止しても投入したリモートのジョブはちゃんと動き続けるので。

**Comment by noda50** [comment]
２つ目のoacis を起動するわけではない。
異なるマシンで別々に oacis を動かしているが、開発環境として rsync で同期共有する領域に置いてあるために生じている、ということ。

現状は、rsync 管理下にないところ (~/var のような directory) に、oacis をまるごとコピーしてから起動する、というスクリプトを別途用意することで、一応、この問題は回避している。

ただ、一般に利用してもらうシステムとしては、非常にトリッキーな構成になっていると感じる。oacis を利用したツール群の開発が、やりにくい。

**Comment by noda50** [comment]
今回の最初の issue であった、並列実行におけるトラブルは、上記の、「実行用に別 directory にコピーして実行」を行うことで、問題は解消したようなので、issue としては close する。
（300並列で 20万 run させたが、特に問題を生じないことを確認）
