### ISSUE TITLE
各ホストのジョブのロードの履歴表示（あったらいいな機能）

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#693]
各 host で、どれくらいの数のジョブをどれくらいかけて流しているか、が表示できないかなー、と思っている。

計算リソースが有効利用できているのか、とか、なにかトラブルが起きてないか、とか。

現在やっている長大ジョブで、並列実行数に波があるように見えるが、それをかんたんにチェックできると嬉しい。

**Comment by noda50** [comment]
なお、波が出てしまう原因は、多分、oacis_watcher でジョブを投げている部分の、不具合（もしくは限界）

**Comment by yohm** [comment]
当面実装できる見込みはないので、まずはAPIをつかって自前で可視化してみてください。
もし他のユースケースにも使える汎用的な仕組みなら以下のリポジトリにコントリビュートしてもらえると嬉しいです。
https://github.com/crest-cassia/oacis_scripts
