### ISSUE TITLE
Simulator を duplicate する時に Object 型の parameter の default が消える

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#696]
Simulator を duplicate する際、Object 型で宣言された parameter の default 値が、もとの Simulator の値を引き継いでいないと思われる。

**Comment by yohm** [comment]
私の環境ではちゃんと引き継いでいるように見えます。ためしにobject型のパラメータを持っているsimulatorを作ってduplicateしてみましたが、このようにデフォルト値が適切に入っていました。
![image](https://user-images.githubusercontent.com/718731/77248101-4bb22f00-6c7a-11ea-8e71-6595f861b691.png)

何か特定の条件で発生するバグかもしれません。再現する条件はわかりますか？

**Comment by noda50** [comment]
試した所、デフォルト値を、 []  (空配列) とすると、引き継げないようです。
{} (空Object) とすると、引き継げました。

**Comment by yohm** [comment]
railsでformを表示するときの問題でした。#697 で修正しました。共有ありがとうございました。
