### ISSUE TITLE
計算ホストでの user ID

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#698]
Oacis が 計算ホストに ssh で xsub を投げる時に、どのユーザIDを使うのか？
それを指定できるようにしたほうがいいのではないか？

状況としては、以下の通り。（混乱避けるため、プログラムの oacis は、Oacis、ユーザ名は oacis）

- 共用のマシン(serverNode)で、Oacis を１つ立ち上げようとしている。予定として複数のユーザがその Oacis を利用する。
- そのために、共用マシンに新しく oacis 用のユーザアカウントを作成。アカウント名は oacis （なんでもいいのだけど）
- その共用マシンにまず、自分の user id (noda) でログインした後、su で oacis にユーザを変更し、 Oacis を立ち上げる。
- 計算ホスト側(calcNode)にも oacis ユーザを用意。
- Oacis の Host 画面で、計算ホスト(calcNode) の登録をしようとすると、 "noda@calcNode に ssh できない" といったエラーが起きる。期待としては、oacis@calcNode に ssh させたい。
- なお、上記で、ssh -> su ではなく、直接、ssh oacis@serverNode とすると、上記の問題は起きない。

つまり、ssh のあと su で user を変更しても、何かを参照して、もとの user 名を使ってしまうようになっている気がする。

**Comment by yohm** [comment]
~/.ssh/config でユーザー名を指定してもダメということでしょうか？

**Comment by noda50** [comment]
それはまだ試していないのだが、変に思うのが、

- su oacis で、calcNode に ssh する際には、ちゃんと、 oacis で login している。
- Oacis から calcNode を host 登録する際には、もとの user id (noda) で login してしまう。

という違い。

**Comment by yohm** [comment]
未検証ですが環境変数のUSERでも参照してるんじゃないですかね？
そもそも別のマシンで無理に同じユーザー名にする必要はなく、普通にconfigで指定すれば大丈夫だと思います。

**Comment by noda50** [comment]
変な設定をすると、その ID を共有する別のユーザが、自分の ID で ssh できてしまうようになり、セキュリティホールになる。それをさけるために、わかりやすさ優先で、同一ユーザ名としておくのが無難。

**Comment by noda50** [comment]
この問題、結局、ruby の net/ssh に起因している。
なので、上記の問題をnet/ssh の開発チームに提起、pull-request を commit して、採用されたので、じきに反映されるはず。
