### ISSUE TITLE
Progress overview の autoload

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#699]
Simulator 画面 の Progress タブの Progress overview において、 "auto reload" を check して、 "Show" を押した後、 Column, Row の軸を変更して再度 "Show" を押すと、 最初に選ばれた軸での表示と、２つめに選んだ軸での表示が、交互（というほど規則的でもないが）に表示されてしまう。

Oacis のバージョンは、 
Version: v3.8.0 , Access Level: 2

**Comment by takeshi-uchitane** [comment]
## 原因調査
https://github.com/crest-cassia/oacis/blob/4fb38fdc6d7958d69a6807ad79c37fe13f2802af/app/views/simulators/_progress.html.haml#L74
最初にShowボタンが押された時にsetIntervalに与えるfunctionが2度目以降にShowボタンを押しても生きているのが原因だと考えられる．

## 対策案
setIntervalに与える関数を変数として記憶し，Showボタンが押されるたびにsetIntervalに与える関数を新しいものに置き換える．
- 注：setInterval関数はページ読み込みで1回だけ読み込まれ常駐するもの（消したらNG）
