### ISSUE TITLE
Run の About の created at のフォーマット

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#701]
Run の About の created at のフォーマット が、
            2020-04-16 20:51:56 +0900
となっている。
他のところの時刻のフォーマットが、
            2020-04-16T21:16:27+09:00
となってる (日付と時刻の間が "T"、 "+09:00" の前にスペースがない）

統一したほうがいいのでは？

**Comment by noda50** [comment]
よく見ると、"update at" の時刻表示も、"T" なし形式。

**Comment by yohm** [comment]
#707 にて修正しました
