### ISSUE TITLE
シミュレータバージョンの解釈

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#702]
Simulator が返す Version 情報の扱いについて、現在、スペースで区切って、その最初の単語だけを Version として扱っている。

これを、返される Version 情報の文字列全体にできないか？

**Comment by yohm** [comment]
私のところでは空白が入ってても文字列全体がversionとして認識されます。どうすれば再現するかわかりますか？

**Comment by noda50** [comment]
これについて、こちらの script のバグであることが判明。
お騒がせして申し訳ない。
