### ISSUE TITLE
Object 型 のParameter で、配列をデフォルト値とした時の duplicate の挙動 

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#708]
Object 型の Parameter のデフォルト値（初期値）に対して、配列の値 (例えば [1,2,3]) を与えた時、duplicate すると、その初期値が変になる。
具体的には、 [1,2,3] が設定されていると、duplicate した時には、それが、 
    1 2 3
という感じになる。（配列の要素が空白で区切られて並ぶ）
当然、この形式はObjectとしてはエラーなので、 create すると、エラーが起きる。

なお、run を生成する時は何の問題もない。（初期値は正しく、[1,2,3] が与えられる)

**Comment by yohm** [comment]
#696 と同じ問題でした。 #697 で修正ずみで次のリリースで修正されます。急ぎで必要な場合はdevelopブランチを使ってください。
