### ISSUE TITLE
String 型の Parameter で列挙した時の挙動

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#709]
String 型の Parameter に対し、Parameter Set を作る際に、列挙の書き方で挙動が変わる。

具体的には、"foo", "bar", "baz" の３つを値として与えたい時、

     foo,bar,baz
     foo, bar, baz
     "foo","bar","baz"

の場合は、期待通りに動くが、

    "foo", "bar", "baz"
    （, の後ろにスペースがある)

では、"foo", "\"bar\"", "\"baz\"" が値として使われる。
つまり、最初の値だけ、引用符がなくなり、の頃は引用符が値の一部として扱われる。

なお、最後の例で、"foo" の前に空白を入れると、"bar" 以降と同じく、引用符が値の一部となる。

Ruby の CSV の解釈ルーチンの限界かな。

**Comment by yohm** [comment]
解釈ルーチンの限界というよりは、どちらかといえばCSVの仕様の問題ですね。
CSVの仕様にはいろいろな亜種があるのですが、基本的にRFC4180が比較的厳密に定められた標準的な仕様です。この仕様ではコンマの直前直後のダブルクオートはパースします。逆にコンマの直後にスペースが入っている`"`はパースしないのが正しい仕様にのっとった挙動で、ご指摘の動作はバグではないです。

（ちなみにテクニカルな話になりますが）oacisはrubyの`CSV.parse`メソッドに`liberal_parsing: true`をセットして実行しています。なのでRFC4180を必ずしも厳密に適用するわけではなく、少し「緩い」仕様を使っています。
参考 : https://qiita.com/yohm/items/c3dde4acf0781fa442ea
