### ISSUE TITLE
ジョブ完了通知機能の追加

### ISSUE THREAD

**Issue by morimorihoge** [crest-cassia/oacis#712]
要件より

```
実行したジョブが完了した時点で利用者に通知する機能を追加実装する。
画面右上に通知を表示するインターフェースを実装し、同時にslackにも通知を送る機能を実装する。
また、通知の粒度をコントロールするための設定画面も実装すること。
```

・フロントエンド側は通知のためのインターフェースモックなどから着手
・バックエンド側はバックエンド側の通知実装をどうするかの検討を行う（Redisがあるのでそのpub/subを使う？など）

**Comment by morimorihoge** [comment]
フロントエンドUIとしては、

* GitHubの右上通知ベルアイコンの様なものがある
* クリックすると画面遷移するのではなく、吹き出しで開いて直近の通知が見れる

程度のモノを想定している。

バックエンド周りは現状ActionCable（Redisバックエンド）でParameterSetページでのJob進行状況通知が行われているので、そちらの実装を参考にするとよさそう（app/assets/javascripts/channels/status.jsあたり）

**Comment by morimorihoge** [comment]
通知UIのイメージを作成してみました。現状では通知一覧にはWorkerLogをそのまま利用する想定でいます。

以下の方針で作成しています。

* 右上に通知アイコンを設置
* dropdown menuでクリックすると開く
* WorkerLogのメッセージ内容はcreated_at＋短めのテキストHTML（levelに応じて出し分けする？）
    * 以下スクリーンショットでは`min-width: 400px` です。調整可能です

![image](https://user-images.githubusercontent.com/818249/103960564-c7dc1b80-5195-11eb-845a-5e88eb8550ca.png)

これとは別に、表示しきれなかった古い通知を見るための

* 通知一覧を表示するページ（ページング付き？）

が必要になると想定しています。

取り急ぎ、ぱっと見でコメントなど頂きつつ詳細詰めていきたいと思います。

**Comment by morimorihoge** [comment]
WorkerLogの粒度と通知したい粒度が異なるため、実装としてはNotificationEventとして新たにModelを作成し、Notificationを出したいタイミングで追加していくことにする。

NotificationEventはMongoDBのCapped Collectionを使えばログローテーションも考えなくて良くなるので、これを使うのがよさそう。
保存するイベントメッセージのサイズとしては長くても通知窓の中で2行を超えない程度のものになるので、詳細ページは不要ということで良い。
※Run IDへのリンクはそもそもメッセージ内をHTMLで保存するなどすれば、拡張性を保ちつつやれるだろう

通知粒度については以下の粒度がGlobalな設定テーブルにlevelが1-3で設定できれば良い。
※現在保存先がないので、Settingsテーブル的なものを作ってそこに保存する

より詳細度の高い粒度が選択された場合、それより広い粒度の通知も表示される。

* 粒度level 1：Simulator単位：配下のRunが全部終わったときと、配下のAnalysisが全て終わったとき両方通知
* 粒度level 2： [Simulator, ParameterSet]単位
* 粒度level 3： [Simulator, ParameterSet, Run]単位

例）「[Simulator, ParameterSet]単位」を選択している場合、Simulator単位の通知も混ざって表示される

※現時点では特定のSimulatorだけ粒度を変えたい、といったものは気にしなくて良い

Analyzerはどうする？

* 粒度level 2： [ParameterSet]単位
* 粒度level 3： [ParameterSet, Run]単位

利用方法として、この通知機能は終了通知として利用するもので、Runが始まったかどうかは既存のRunsページがあるので、そちらを見てもらえば良い。

**Comment by morimorihoge** [comment]
NotificationEventの保存方針としては、Eventが発生した時点でのGlobal設定に従ってEventを生成する。

例）

* 粒度level 1で設定する
* Runをし始める
* Runが一通り終わり、Simulator完了Eventが生成される（通知もされる）
* 粒度levelを2に変更する
* NotificationEventsの中はSimulator完了Eventのみが残っている（粒度Level1の時のLevel2のEventは生成されないで良い）

**Comment by kimurabps** [comment]
@yohm 

通知機能の仕様について何点か質問がございますので、お手数ですがご回答のほどお願いいたします :bow:
1.  ベルマークの右上にドットをつける or 未読件数をバッジで表示するなどして、通知の有無を知らせる機能は必要でしょうか？
<img width="478" alt="badge" src="https://user-images.githubusercontent.com/38060535/106116110-e2058a00-6194-11eb-83e4-ed3c2c773519.png">


2. 1に関連して、画面をリロードしても未読状態の維持は必要でしょうか？ (必要な場合は、未読状態をDBに持たせるようにしようかと思います :bow: )

4. 通知のタイミングは以下の通りでよろしいでしょうか？ もし過不足等がございましたら、ご指摘お願いいたします :bow:

- 粒度level 1 (Simulator単位) の場合:
  - Simulator配下のRunが全部終わった時
  - Simulator配下のAnalysisが全部終わった時
 (計2回通知)

- 粒度level 2 ([Simulator, ParameterSet]単位) の場合:
  粒度level 1の通知に加えて、以下のタイミングで通知する
  - ParameterSet配下のRunsが全部終わった時
  - ParameterSet配下のAnalysisが全部終わった時
- 粒度level 3 ([Simulator, ParameterSet, Run]単位) の場合:
粒度level 1, 2の通知に加えて、以下のタイミングで通知する
  - 各Runが終わった時
  - 各Analysisが終わった時

※通知の文言は `All run / analysis finished in SimulatorID #{idのリンク}.`, `RunID / AnalysisID #{idのリンク} finished.` のような文言を想定しております :bow:

**Comment by yohm** [comment]
@kimurabps 

ご確認ありがとうございます。

> 1. ベルマークの右上にドットをつける or 未読件数をバッジで表示するなどして、通知の有無を知らせる機能は必要でしょうか？

ぜひこのようなバッジが欲しいです。

> 2. 1に関連して、画面をリロードしても未読状態の維持は必要でしょうか？

できれば未読状態を維持したいです。DBに持たせるようにしていただけますでしょうか

> 3. 通知のタイミングは以下の通りでよろしいでしょうか？

はい。間違いありません。通知の文言もご提案の通りでお願いします。

**Comment by kimurabps** [comment]
承知いたしました。ご回答ありがとうございます :bow:

**Comment by morimorihoge** [comment]
@kimurabps モックアップを作成した際のCSSが僕の手元にしかないのでこの後送ります

**Comment by morimorihoge** [comment]
定例にてmerge済み確認しましたので完了とします。
