### ISSUE TITLE
ParameterSet のテーブルにおけ るフィルター機能のUI 改善を ⾏う

### ISSUE THREAD

**Issue by morimorihoge** [crest-cassia/oacis#715]
現状では、既存のフィルターの名前を編集したり、条件を更新することができない問題点を解決する。

以下現行仕様

![image](https://user-images.githubusercontent.com/818249/101851343-b4da2980-3b9e-11eb-88a8-908af4507a51.png)

![image](https://user-images.githubusercontent.com/818249/101851269-92481080-3b9e-11eb-9f7b-56e2fa52e7b6.png)

**Comment by morimorihoge** [comment]
本件としては、Filtersモーダルの中に以下のようなよくある編集アイコンを追加し、それを押すことで編集できるようにするといったモノを想定しています。

![image](https://user-images.githubusercontent.com/818249/103962531-826e1d00-519a-11eb-9e5a-44475346d4a5.png)

**Comment by yusiro-bps** [comment]
@yohm 以下のように、Filtersの編集アイコンからフィルター名、条件を更新できるようにしようかと思っていますが、このイメージで問題ないでしょうか。
他の動きのイメージなどあればご指摘いただけると助かります。

![image](https://user-images.githubusercontent.com/49134429/104533308-7e884200-5655-11eb-9875-018ce6c61392.png)

![image](https://user-images.githubusercontent.com/49134429/104537400-4127b280-565d-11eb-8b3c-710fe60e1fe5.png)

![image](https://user-images.githubusercontent.com/49134429/104533347-8fd14e80-5655-11eb-932f-24b5c3afcfee.png)

**Comment by morimorihoge** [comment]
定例にて大枠OK頂きましたので、こちらで進めて微調整あればPRで対応しましょう。

**Comment by morimorihoge** [comment]
本件、定例にて確認頂きましたのでcloseします。
