### ISSUE TITLE
ParameterSet のテーブルのUI 改善

### ISSUE THREAD

**Issue by morimorihoge** [crest-cassia/oacis#716]
UIの改善を行い、選択しやすい状態にする。具体的には以下のような項目を改善すること。

* テーブルでパラメータの表示の順番を変更したり非表示にする機能を実装する
* その表示についての情報を保存しておいて次に開いたときに再現できるようにする
* パラメータの値によって大小によってセルに色付けを行う
* スクロールしてもパラメータの名前が表示されるようにする
* 画面上部にも次のページ、前のページに移動するボタンをつける

実装方針的に #715 と被る部分も多そうなので、平行して検討していく。

**Comment by morimorihoge** [comment]
フィルタ機能との関連もあるため、一回どういう感じの制限の上でやるかを考えた方が良さそうです。

* Filterは現状サーバーサイドでやっているので、非表示になっている項目で絞り込むのは特に問題なさそう
* 表示非表示のUIをどうするか？
    * 現状のshow / hide機能とそれほど変えなくて良い
* 順番変更のUIをどうするか？
    * 列のヘッダ部分をD&Dするといい感じに入れ替わるようなもので良い
* 表示非表示・順番変更の状態を保持するのか？および保持する範囲はどうするのか？（ParameterSet内で保持するのか、Simulatorレベルで保持するのか）
    * Simulatorレベルで良い

まずは上記を見つつ、どんな感じで実装できそうか検討します。

**Comment by yusiro-bps** [comment]
@yohm 

- 列の順番を変更する
- スクロールしてもパラメータの名前が表示されるようにする
- 画面上部にも次のページ、前のページに移動するボタンをつける

![Untitled](https://user-images.githubusercontent.com/49134429/106688931-697a4f80-6612-11eb-937d-4eaa5bd14161.gif)


上記３点、このイメージでいますが、認識違う点ありましたらご指摘いただけると助かります。

> パラメータの値によって大小によってセルに色付けを行う

このイメージがついておらず、ざっくりどういうイメージか教えていただけると助かります:pray:

**Comment by yohm** [comment]
@yusiro-bps ありがとうございます！イメージ通りです。動かせる列はUpdated_at よりも後のパラメータの値が書いてある箇所だけで大丈夫です。

> パラメータの値によって大小によってセルに色付けを行う

こちらの意図としては、数値がザーッと並んでいる表を眺めてもどの項目が大きいのか小さいのかすぐにわかりにくいという点をどうにか改善したいと考えています。
例えば上の画像の例でいえば"l"の値を色々と変えていますが、lの値が大きいものに赤を、小さいものに青色をつけて、セルの値の大小が色でわかるようにしたいです。

実装方針としては、表示されているものを列ごとに値を大小で順序づけて、順位に応じて色をグラデーションにして色を付けると言うようなものを想定しています。数値型のパラメータのみでOKです。
サーバーサイドで処理してもクライアントサイドで処理しても良いと思うのですが、どちらで実装するかはお任せいたします。

**Comment by yusiro-bps** [comment]
ご回答ありがとうございます。承知しました。

**Comment by morimorihoge** [comment]
定例にて完了確認済み。
