### ISSUE TITLE
ParameterSet のページにおいて配下のRunの結果の特定のファイルを⼀覧を表⽰する 機能を追加する

### ISSUE THREAD

**Issue by morimorihoge** [crest-cassia/oacis#718]
現行イメージ

![image](https://user-images.githubusercontent.com/818249/101854278-8f501e80-3ba4-11eb-9ec4-3a3fb77fd40b.png)

できあがりのUIイメージから検討していきたい。

![image](https://user-images.githubusercontent.com/818249/101854649-48165d80-3ba5-11eb-9a4e-7c3b9a3f2276.png)

**Comment by morimorihoge** [comment]
Plotタブの右に「Files」タブを用意し、

* Filesタブの中に「ファイルリスト選択」のセレクトボックスがある
    * 選択候補はそのParameterSetで最初に成功したJobのResultsから取る
* ファイルを選択すると、Runsタブ相当のテーブルでそのファイルをプレビューした一覧が表示される
    * 画像ファイルであればIMGタグで埋め込む
    * 現在表示しているファイル一覧をまとめてDLするリンクが欲しい
        * ファイル名はシステム側でRun IDを付けるなどの対応が必要
        * このファイルは基本的に同条件で実行した処理の結果なので、順番や名前付けはそれほど重要ではないはず（出力したときの一意性は必要なのでRun IDは必要）

**Comment by morimorihoge** [comment]
ファイル選択して表示される一覧TABLEは、Run IDとdetailとしてファイルの内容があるだけの縦に長い表が出るイメージとのこと。

※現行のdataTableできれいに表示されるかはやってみないと分からないので、もし表示が大幅に崩れたり調整が難しいようならPRの中で適宜調整していく（実用上は並べ替え不要（だが、同じ条件なら同じ順序で出て欲しい）なので、普通のtableやlistでも問題ない）

**Comment by kimurabps** [comment]
@yohm 2点質問がございます :bow:
1. 結果ファイルにディレクトリが含まれている場合の扱いはどのようにすればよろしいでしょうか？
例えば以下などが考えられるかと思います :bow:
```
A. ディレクトリは無視して第1階層のファイルまでとする (セレクトボックスにはfile_aのみを表示)
B. ディレクトリ内を再帰的にスキャンしてファイルのみを表示する(セレクトボックスにはfile_a, file_bを表示)

/
　├ file_a
　└ directory/
　　　└ file_b
```
2. 結果ファイルに `{RUN_ID}_xsub.sh` というような、Runごとに名前の異なるファイルが含まれていることがあるようなのですが、このファイルはセレクトボックスから除外してしまっても問題ございませんでしょうか？

以上、お手数ですがご確認のほどよろしくお願いいたします :bow:

**Comment by yohm** [comment]
@kimurabps  質問ありがとうございます。

> 1. 結果ファイルにディレクトリが含まれている場合の扱いはどのようにすればよろしいでしょうか？

おっしゃる通りディレクトリについて検討が漏れていました。案Aの通り第一階層までとしてください。

> 2. 結果ファイルに {RUN_ID}_xsub.sh というような、Runごとに名前の異なるファイルが含まれていることがあるようなのですが、このファイルはセレクトボックスから除外してしまっても問題ございませんでしょうか？

問題ありません。こちらは一覧表示するようなユースケースは想定されませんので除外してください。

**Comment by kimurabps** [comment]
承知いたしました。ご回答ありがとうございます。

**Comment by morimorihoge** [comment]
定例にて内容確認頂き、PRもmerge済みなのでcloseします。
