### ISSUE TITLE
Simulator ページのProgressタブの表⽰改善

### ISSUE THREAD

**Issue by morimorihoge** [crest-cassia/oacis#719]
SimulatorページのProgress タブにおいて、finished, failed, running, submitted, created のRunの数の表示がリアルタイムで更新されるようにすること。また、それらの表示から、それぞれの対応するステータスを持つRun のリストの一覧を表示できるようにすること。

現在ParameterSetのページではオンデマンド更新が実装されているので、そちらと同様に考えれば良いのか？
UI周りなど確認しつつ進めていきたい。

![image](https://user-images.githubusercontent.com/818249/101854974-fb7f5200-3ba5-11eb-8acb-b0f59a3c4212.png)

**Comment by morimorihoge** [comment]
現在の問題として、Progress overviewのshow + auto reloadを有効にすると、Progress overviewの内容はreloadされるが、Number of Runsの値が更新されないというものがある。

あるべき姿として、

* auto reloadのチェックボックスをNumber of Runsの上かどこかの「Progressタブ全体」を対象として見えるような位置に移動
* auto reloadの処理の更新対象をProgressタブ内全体に拡張する

**Comment by kimurabps** [comment]
@yohm 本issueですが、下記のような仕様で問題ございませんでしょうか？ 齟齬等ございましたら、お手数ですがご指摘の程お願いいたします :bow:

```
- auto reloadのチェックボックスが、「Progressタブ全体」を対象として見えるように、Number of Runsの上部に移動する
- Parameter Setsタブと同様、auto reloadのチェックボックスの横に 更新ボタン と 更新間隔の入力ボックス を配置する
- auto reloadの処理の更新対象をProgressタブ内全体に拡張する
```

以下、修正後の画面イメージになります。

<img width="1227" alt="progress" src="https://user-images.githubusercontent.com/38060535/103989125-933a8500-51d2-11eb-91ce-13a1ef649083.png">

**Comment by yohm** [comment]
@kimurabps はい、コメントしていただいた通りのイメージです。現状は"Number of Runs"のテーブルが自動更新されないので、こちらも自動更新されるようにしていただけると助かります。

**Comment by kimurabps** [comment]
ご回答ありがとうございます。承知いたしました。

**Comment by morimorihoge** [comment]
定例MTGにて完了確認したのでcloseします。
