### ISSUE TITLE
Simulator一覧画面でプログレスバーを動的に更新する

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#721]
画面右のプログレスバーが、動的に更新されるようにする。

![image](https://user-images.githubusercontent.com/718731/103112227-59786300-4697-11eb-9651-e360d6c60617.png)

実装方法として (1) 定期的にpollingする (2) ジョブが完了したタイミングでaction cableで通知をもらって更新する の２通りがありうると考えられるが、 #712 の実装方法にも依存すると思われるため #712 の完了後に検討する。

**Comment by morimorihoge** [comment]
action cableで取れそうなので、そちらで実装を進める方向です。

**Comment by morimorihoge** [comment]
定例にてmerge済み確認しましたので完了とします。
