### ISSUE TITLE
ParameterSetのページのFileタブで"_output.json" ファイルの内容を表示したい

### ISSUE THREAD

**Issue by yohm** [crest-cassia/oacis#730]
ParameterSetのFileタブ（あるParameterSet以下のRunの特定のファイルの一覧を表示するページ）において "_output.json" ファイルを指定した場合に、内容を表形式にレンダリングして表示したい。

現状では、"_output.json"の表示を選択した場合

![image](https://user-images.githubusercontent.com/718731/107617182-c620de80-6c92-11eb-9de6-048131a6f4ad.png)

のようになる。OACISにおいて"_output.json"は数値の結果を保存する特殊なファイルなので、このファイルの中身もまとめて表示したい。現状ではRunのページにおいて下のように表形式で表示されるので、この表をFileのタブにおいても一覧で表示したい。

![image](https://user-images.githubusercontent.com/718731/107617429-3d567280-6c93-11eb-8ed7-807145a12f28.png)

**Comment by morimorihoge** [comment]
Run詳細のページで現在出ている項目そのものを出せば良いとのことなので、そちらのコードを見つつ踏襲するのがよさそう。

JSON内の1階層目のパラメータだけを一覧する形式となり、パラメータ数が膨大になってテーブルが爆発するようなことは考慮しなくて良いとのこと。

**Comment by morimorihoge** [comment]
本件定例にて確認できましたのでcloseします。
