### ISSUE TITLE
install document  のアップデートが必要？

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#743]
現在のインストールマニュアルで、おそらく、アップデートが間に合ってないところがあるように思える。
http://crest-cassia.github.io/oacis/ja/install.html

>   rbenv install 2.5.1 && rbenv global 2.5.1
>   rbenv rehash
>   ruby --version
のところで、2.5.1 ではなく、 2.7.2 である必要があると思われる。

**Comment by noda50** [comment]
github の docs の下を直接編集してよいのかわからないので、 issue にあげます。

**Comment by yohm** [comment]
ありがとうございます。 #744 で対応しました。
