### ISSUE TITLE
ssh のテスト

### ISSUE THREAD

**Issue by noda50** [crest-cassia/oacis#754]
OACIS DOC の「インストール」のページ、「(2) 計算ホストのセットアップ」 の「3. (OACISホストにて) 導入の確認」の部分で、ssh の動作確認がこれでは不十分な事例に遭遇した。

~/.ssh/id_rsa のファイルに、最後に無駄な空行があった場合、コマンドラインで `ssh remotehost ...`  を実行できるが、ruby の Net::SSH では、認証エラーとなる。 Net::SSH の不備ではあるが、原因究明にかなり時間がかかった。
最終的に、irb で、
``` 
> require 'net/ssh'
> ssh = Net::SSH.start("remotehost", "oacis", verbose:Logger::DEBUG)
```
を実行してエラーを確認。id_rsa で認証できていないのを確認し、上記の追求ができた。

同様のミスが生じるか不明だが、トラブルシューティング事例としてどこかに載せておきたい。

**Comment by yohm** [comment]
マージしました。ありがとうございます。
